force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <displayFormat>ENG-{0000000000}</displayFormat>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement_Name_Tag__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Name_Tag__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Engagement Name Tag</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MobilitySharingTestDataFactory.cls
@isTest
public class MobilitySharingTestDataFactory {
    
    
    @isTest
    private static void makeObjects(){
		String jsonString = new MobilityTestRecordBuilder()
            .withObjectType(Account.SObjectType)
            .build()
            .getObjectString();
        
        System.debug(jsonString);
    }
    
    @isTest
    private static void makeObjectWithChildRecords(){
        Id fakeId = TestUtility.getFakeId(Account.SObjectType);
        List<String> contactStrings = new List<String>();
        for(Integer i = 1; i<2; i++){
            Map<String, String> fields = new Map<String, String>();
            fields.put('FirstName', 'TestContact');
            fields.put('LastName', String.valueOf(i));
            contactStrings.add(new MobilityTestRecordBuilder().withObjectType(Contact.SObjectType).withFields(fields).build().getObjectString());
        }
        System.debug('contact Strings  '+contactStrings);
        String jsonString = new MobilityTestRecordBuilder()
            .withObjectType(Account.SObjectType)
            .withChildRecords('Contacts', contactStrings)
            .build()
            .getObjectString();
        
        System.debug(jsonString);
        Account a = (Account)JSON.deserialize(jsonString, Account.class);
        System.debug(JSON.serialize(a));
    }
    
    @isTest
    private static void makeObjectWithParentRecords(){
        Map<String, String> accountFields = new Map<String, String>();
        accountFields.put('Name','TEST');
        accountFields.put('BillingPostalCode','14221');
        String accountString = new MobilityTestRecordbuilder().withObjectType(Account.SobjectType).withFields(accountFields).build().getObjectString();
        
        Map<String, String> engagementFields = new Map<String, String>();
        engagementFields.put('Engagement_Name_Tag__c', 'TEST ENGAGEMENT');
        String jsonString = new MobilityTestRecordBuilder().withObjectType(Engagement__c.SobjectType).withParentRecords('Client__r', accountString).build().getObjectString();
        System.debug('jsonstring: '+jsonString);
		Engagement__c eng = (Engagement__c)JSON.deserialize(jsonString, Engagement__c.class); 
system.debug(JSON.serialize(eng));        
    }
}