force-app/main/default/objects/Consent__c/Consent__c.object-meta.xml
<CustomObject>
    <label>Consent</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Consent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Consent__c/fields/Consent_Form__c.field-meta.xml
<CustomField>
    <fullName>Consent_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consent Form</label>
    <referenceTo>Consent_Form__c</referenceTo>
    <relationshipLabel>Consents</relationshipLabel>
    <relationshipName>Consents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consent__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consent_Form__c/Consent_Form__c.object-meta.xml
<CustomObject>
    <label>Consent Form</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Consent Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consent Forms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Consent_Form__c/fields/Applicable_to_All__c.field-meta.xml
<CustomField>
    <fullName>Applicable_to_All__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To indicate the consent form is applicable to everyone.</description>
    <label>Applicable to All</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Consent_Form__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ConsentsDao.cls
public with sharing class ConsentsDao {
    
    public void insertConsents(List<Consent__c> consents){
        insert consents;
    }

    public List<Consent_Form__c> fetchActiveUniversalConsentForms(){
        return [SELECT Id, Name FROM Consent_Form__C WHERE Status__c= 'Active' and Applicable_To_All__c = true];
    }
    
    public User fetchCosentRelatedUser(Id userId){
        return [SELECT Id, FirstName, LastName FROM User WHERE Id =: userId LIMIT 1];
    }
    
}