force-app/main/default/objects/Consent__c/Consent__c.object-meta.xml
<CustomObject>
    <label>Consent</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Consent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Consent__c/fields/Consent_Form__c.field-meta.xml
<CustomField>
    <fullName>Consent_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consent Form</label>
    <referenceTo>Consent_Form__c</referenceTo>
    <relationshipLabel>Consents</relationshipLabel>
    <relationshipName>Consents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consent__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to link Client Contacts and Staff (Andersen or Affiliate) to Consents</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consents</relationshipLabel>
    <relationshipName>Consents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consent__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Consents</relationshipLabel>
    <relationshipName>Consents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consent_Form__c/Consent_Form__c.object-meta.xml
<CustomObject>
    <label>Consent Form</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Consent Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consent Forms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ConsentsTest.cls
@isTest 
public with sharing class ConsentsTest {

    @isTest 
    private static void itShouldFetchForms(){
        Stub daoStub = new Stub(ConsentsDao.class);
        daoStub.setReturnValue('fetchActiveUniversalConsentForms', new List<Consent_Form__c>());

        Consents bso = new Consents();
        bso.dao = (ConsentsDao)daoStub.instance;

        List<Consent_Form__c> results;

        test.startTest();

        results = bso.getConsentFormsForNewUsers();

        test.stopTest();
        
        daoStub.assertInvoked('fetchActiveUniversalConsentForms');
        System.assert(results.isEmpty());

    }
    
    @isTest 
    private static void itShouldFetchUser(){
        Stub daoStub = new Stub(ConsentsDao.class);
        daoStub.setReturnValue('fetchCosentRelatedUser', new User());

        Consents bso = new Consents();
        bso.dao = (ConsentsDao)daoStub.instance;
        
		User fakeUser = new User(Id=TestUtility.getFakeId(User.SObjectType), FirstName='Joe', LastName='Smith');
        
        User results;

        test.startTest();

        results = bso.getCosentRelatedUser(fakeUser.Id);

        test.stopTest();
        
        daoStub.assertInvoked('fetchCosentRelatedUser');
        //System.assert(results.isEmpty());

    }

    @isTest 
    private static void itShouldSaveforms(){
        Stub daoStub = new Stub(ConsentsDao.class);
        daoStub.setReturnValue('insertConsents', null);

        Consents bso = new Consents();
        bso.dao = (ConsentsDao)daoStub.instance;

        test.startTest();

        bso.saveConsents(new List<Consent__c>());

        test.stopTest();
        
        daoStub.assertInvoked('insertConsents');
    }

    @isTest
    private static void itSHouldMakeAConsentFormForAContact(){
        User fakeUser = new User(Id=TestUtility.getFakeId(User.SObjectType), FirstName='Joe', LastName='Smith');
        Id linkedRecordId = TestUtility.getFakeId(Contact.sObjectType);
        Consent_Form__c form = new Consent_Form__c(Name='Fake Consent', Id=TestUtility.getFakeId(Consent_Form__c.SObjecttype));

        Consent__c result;

        test.startTest();
        
        result = new Consents().makeConsentForUser(linkedRecordId, fakeUser, form);

        test.stopTest();

        System.assertEquals(null, result.Individual__c);
        System.assertEquals(linkedRecordId, result.Contact__c);

    }

    @isTest 
    private static void itShouldMakeAConsentFormForAPersonAccount(){
        User fakeUser = new User(Id=TestUtility.getFakeId(User.SObjectType), FirstName='Joe', LastName='Smith');
        Id linkedRecordId = TestUtility.getFakeId(Account.sObjectType);
        Consent_Form__c form = new Consent_Form__c(Name='Fake Consent', Id=TestUtility.getFakeId(Consent_Form__c.SObjecttype));

        Consent__c result;

        test.startTest();
        
        result = new Consents().makeConsentForUser(linkedRecordId, fakeUser, form);

        test.stopTest();

        System.assertEquals(null, result.Contact__c);
        System.assertEquals(linkedRecordId, result.Individual__c);

    }
}