force-app/main/default/objects/Engagement_Assignee__c/Engagement_Assignee__c.object-meta.xml
<CustomObject>
    <label>Mobile Employee</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Mobile Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobile Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Assignee__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mobile Employees</relationshipLabel>
    <relationshipName>Engagement_Assignees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>JIRA:AGMPB-257</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/User/fields/Share_Email_with_Employer__c.field-meta.xml
<CustomField>
    <fullName>Share_Email_with_Employer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>JIRA:AGMPB-592</description>
    <label>Share email address update with employer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TA_UserCEventSetAccEmail.cls
public class TA_UserCEventSetAccEmail implements TriggerAction.AfterInsert {

    @testVisible
    public UserChangeEventDao dao;

    public TA_UserCEventSetAccEmail() {
        this.dao = new UserChangeEventDao();
    }

    public void AfterInsert(List<UserChangeEvent> newList) {
        handleUserEmailChange(newList);
    }

    @testVisible
    public void handleUserEmailChange(List<UserChangeEvent> events) {
        Set<String> userIds = new Set<String>();

        for (UserChangeEvent event : events) {
            EventBus.ChangeEventHeader header = event.ChangeEventHeader;
            if (header.changedFields.contains('Email') && header.changeType == 'Update') {
                userIds.addAll(header.RecordIds);
            }
        }

        if (userIds.isEmpty()) return;

        List<User> userList = dao.getActiveAssigneePortalUsers(userIds);
        if (userList.isEmpty()) return;

        Map<String, User> accIdToUserMap = new Map<String, User>();
        List<Account> accountsToUpdate = new List<Account>();

        for (User usr : userList) {
            if (usr.AccountId != null) {
                accountsToUpdate.add(new Account(
                    Id = usr.AccountId,
                    Primary_Email__pc = usr.Email,
                    Agree_to_Share_Email__pc = usr.Share_Email_with_Employer__c
                ));
                accIdToUserMap.put(usr.AccountId, usr);
            }
        }

        if (!accountsToUpdate.isEmpty()) {
            update accountsToUpdate;
        }

        Map<Id, Engagement_Assignee__c> engagementAssigneeMap =
            dao.getEngagementAssigneesByAssignee(accIdToUserMap.keySet());

        List<Engagement_Assignee__c> engagementAssigneesToUpdate = new List<Engagement_Assignee__c>();

        for (Engagement_Assignee__c ea : engagementAssigneeMap.values()) {
            User user = accIdToUserMap.get(ea.Assignee__c);
            if (user != null && user.Share_Email_with_Employer__c) {
                ea.Email__c = user.Email;
                engagementAssigneesToUpdate.add(ea);
            }
        }

        if (!engagementAssigneesToUpdate.isEmpty()) {
            update engagementAssigneesToUpdate;
        }
    }
}