force-app/main/default/objects/Engagement_Assignee__c/Engagement_Assignee__c.object-meta.xml
<CustomObject>
    <label>Mobile Employee</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Mobile Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobile Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Assignee__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mobile Employees</relationshipLabel>
    <relationshipName>Engagement_Assignees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>JIRA:AGMPB-257</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/User/fields/Share_Email_with_Employer__c.field-meta.xml
<CustomField>
    <fullName>Share_Email_with_Employer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>JIRA:AGMPB-592</description>
    <label>Share email address update with employer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UserChangeEventDao.cls
public class UserChangeEventDao {
 public List<User> getActiveAssigneePortalUsers(Set<String> userIds) {
        return [
            SELECT Id, AccountId, Email, IsActive, Profile.Name, Share_Email_with_Employer__c 
            FROM User 
            WHERE IsActive = true 
              AND Profile.Name = 'Assignee Portal' 
              AND Id IN :userIds
        ];
 }
      public Map<Id, Engagement_Assignee__c> getEngagementAssigneesByAssignee(Set<String> assigneeIds) {
        return new Map<Id, Engagement_Assignee__c>(
            [SELECT Id, Assignee__c, Email__c 
             FROM Engagement_Assignee__c 
             WHERE Assignee__c IN :assigneeIds]
        );
    
    }
}