force-app/main/default/objects/ace_File__c/ace_File__c.object-meta.xml
<CustomObject>
    <description>Contains metadata associated to a file. This metadata persists even when the file itself is deleted.</description>
    <label>Shared File</label>
    <nameField>
        <displayFormat>af-{000000}</displayFormat>
        <label>File ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared Files</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ace_File__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>JIRA:AGMPB-249</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>A_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Work_Record__c.field-meta.xml
<CustomField>
    <fullName>Work_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Record</label>
    <referenceTo>Work_Record__c</referenceTo>
    <relationshipName>Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <displayFormat>ENG-{0000000000}</displayFormat>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Record__c/Work_Record__c.object-meta.xml
<CustomObject>
    <label>Work Record</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Record__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TA_CDL_CreateShareFilesDirectCDLSTest.cls
@isTest
public with sharing class TA_CDL_CreateShareFilesDirectCDLSTest {

    @isTest
    private static void itShouldOnlyRunOnMappedFiles(){
        Stub filesStub = new Stub(Files.class);
        Stub aFilesStub = new Stub(ace_Files.class);

        filesStub.setReturnValue('addNewContentDocumentLinks', null);
        filesStub.setReturnValue('removeContentDocumentLinks', null);
        aFilesStub.setReturnValue('saveNewFiles', null);        
        Id contentdocumentId = TestUtility.getFakeId(ContentDocument.SObjectType);
        Id contentDocumentLinkId = TestUtility.getFakeId(ContentDocumentLink.SObjectType);
        Id recordId = TestUtility.getFakeId(Case.SObjectType);

        ContentDocumentLink cdl = new ContentDocumentLink(Id=ContentDocumentLinkId, ContentDocumentId = contentdocumentId, LinkedEntityId = recordId);
    
        TA_CDL_CreateSharedFilesForDirectCDLS ta = new TA_CDL_CreateSharedFilesForDirectCDLS();
        
        test.startTest();

        ta.afterInsert(new List<ContentDocumentLink>{cdl});

        test.stopTest();

        System.assertEquals(0, ta.inserts.size());
        filesStub.assertNotInvoked('addNewContentDocumentLinks');
    }

    @isTest
    private static void itShouldSetTheAppropriateLookup(){
        Stub filesStub = new Stub(Files.class);
        Stub aFilesStub = new Stub(ace_Files.class);

        filesStub.setReturnValue('addNewContentDocumentLinks', null);
        filesStub.setReturnValue('removeContentDocumentLinks', null);
        aFilesStub.setReturnValue('saveNewFiles', null);        
        Id contentdocumentId = TestUtility.getFakeId(ContentDocument.SObjectType);
        Id contentDocumentLinkId = TestUtility.getFakeId(ContentDocumentLink.SObjectType);
        Id recordId = TestUtility.getFakeId(Engagement__c.SObjectType);

        TA_CDL_CreateSharedFilesForDirectCDLS ta = new TA_CDL_CreateSharedFilesForDirectCDLS();
        ta.files = (Files)filesStub.instance;
        ta.aFiles = (ace_Files)aFilesStub.instance;

        ContentDocumentLink cdl = new ContentDocumentLink(Id=ContentDocumentLinkId, ContentDocumentId = contentdocumentId, LinkedEntityId = recordId);

        test.startTest();

        ta.afterInsert(new List<ContentDocumentLink>{cdl});

        test.stopTest();
        System.assertEquals(1, ta.inserts.size(), 'expect one shared file');
        
        ace_File__c record = ta.inserts[0];
        System.assertEquals(true, record.Engagement__c == cdl.LinkedEntityId, 'expect to be linked to the engagement');
        System.assertEquals(true, record.Work_Record__c == null, 'expect no work record');
        filesStub.assertInvoked('addNewContentDocumentLinks');
        filesStub.assertInvoked('removeContentDocumentLinks');
        afilesStub.assertInvoked('saveNewFiles');
        
    }


}