force-app/main/default/objects/ace_File__c/ace_File__c.object-meta.xml
<CustomObject>
    <description>Contains metadata associated to a file. This metadata persists even when the file itself is deleted.</description>
    <label>Shared File</label>
    <nameField>
        <displayFormat>af-{000000}</displayFormat>
        <label>File ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared Files</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ace_File__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>JIRA:AGMPB-249</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>A_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Internal_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Internal_Review_Status__c</fullName>
    <description>Describes the status of an Ace File prior to sharing it externally with customer users.</description>
    <label>Internal Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <displayFormat>ENG-{0000000000}</displayFormat>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ace_FilesDaoTest.cls
@isTest
public class ace_FilesDaoTest {
    
    @isTest
    static void aceFilesDao(){
        List<ace_File__c> filesToUpdate = new List<ace_File__c>();
        ace_FilesDao fileDao = new ace_FilesDao();
        
        Id fakeEngagementId = TestUtility.getFakeId(Engagement__c.SObjectType);
        ace_File__c mockFile = new ace_File__c(
            Id = TestUtility.getFakeId(ace_File__c.SObjectType),
            Engagement__c = fakeEngagementId
        );
        
        String message;
        Test.startTest();
        try{
            fileDao.saveAceFiles(filesToUpdate);
            fileDao.fetchFilesByEngagementId(fakeEngagementId);
            fileDao.fetchEngagementsWithFiles(5,0);
			List<ClientDocumentCenterCtrl.EngagementSummary> summaries = fileDao.fetchEngagementsWithFiles(5,0);            
            fileDao.fetchVisibleFiles();
        } catch (Exception e) {
            message = e.getMessage();
        }
        Test.stopTest();
        System.assertEquals(true, String.isEmpty(message));
    }

    @isTest
    private static void testFetchAceFilesVisibleToExternalAudiencesById() {
        List<ace_File__c> existingFiles = new List<ace_File__c>{new ace_File__c(
            Id = TestUtility.getFakeId(ace_File__c.SObjectType),
            Internal_Review_Status__c = 'Approved'
        )};
        Set<Id> fileIds = new Set<Id>();
        for (ace_File__c file : existingFiles) {
            fileIds.add(file.Id);
        }
        ace_FilesDao dao = new ace_FilesDao();

        
        Test.startTest();
        List<ace_File__c> result = dao.fetchAceFilesVisibleToExternalAudiencesById(fileIds);
        Test.stopTest();

    }
    
}