force-app/main/default/objects/ace_File__c/ace_File__c.object-meta.xml
<CustomObject>
    <description>Contains metadata associated to a file. This metadata persists even when the file itself is deleted.</description>
    <label>Shared File</label>
    <nameField>
        <displayFormat>af-{000000}</displayFormat>
        <label>File ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared Files</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ace_File__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>JIRA:AGMPB-249</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>A_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <description>JIRA:AGMPB-437</description>
    <encryptionScheme>None</encryptionScheme>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <description>JIRA:AGMPB-437</description>
    <encryptionScheme>None</encryptionScheme>
    <label>File Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the Person Account individual</description>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shared Files</relationshipLabel>
    <relationshipName>Shared_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Internal_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Internal_Review_Status__c</fullName>
    <description>Describes the status of an Ace File prior to sharing it externally with customer users.</description>
    <label>Internal Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Internal_Visibility__c.field-meta.xml
<CustomField>
    <fullName>Internal_Visibility__c</fullName>
    <description>Used by internal Andersen users to indicate who a Shared File record should be shared with.</description>
    <label>Internal Visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All Firms on Engagement</fullName>
            </value>
            <value>
                <fullName>Coordinating Country</fullName>
            </value>
            <value>
                <fullName>Country-Specific</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Shared_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Shared_File_Name__c</fullName>
    <description>JIRA:AGMPB-774</description>
    <formula>HYPERLINK(
  LEFT(
    $Api.Partner_Server_URL_260,
    FIND(&apos;/services&apos;, $Api.Partner_Server_URL_260)
  ) &amp; &apos;/&apos; &amp; Id,
  IF(
    NOT(ISBLANK(File_Name__c)),
    File_Name__c &amp;
      IF(
        NOT(ISBLANK(File_Type__c)),
        &quot;.&quot; &amp; File_Type__c,
        Name
      ),
    Name
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shared File Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Subscribed_Office__c.field-meta.xml
<CustomField>
    <fullName>Subscribed_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the Shared File to a specific office, so the office can see it,.</description>
    <label>Subscribed Office</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>If there is an Engagement related to a Shared File, only Subscribed Office related to the same engagement can be added.</errorMessage>
        <filterItems>
            <field>$Source.Engagement__c</field>
            <operation>equals</operation>
            <valueField>Subscribed_Offices__c.Engagement__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Engagement__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscribed_Offices__c</referenceTo>
    <relationshipLabel>Shared Files</relationshipLabel>
    <relationshipName>Shared_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Upload_Date__c.field-meta.xml
<CustomField>
    <fullName>Upload_Date__c</fullName>
    <description>JIRA:AGMPB-437</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Upload Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Uploaded_By__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who uploaded the file attached to this record?</description>
    <label>Uploaded By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UploadedFiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Work_Record__c.field-meta.xml
<CustomField>
    <fullName>Work_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Record</label>
    <referenceTo>Work_Record__c</referenceTo>
    <relationshipName>Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <displayFormat>ENG-{0000000000}</displayFormat>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Coordinating_Office__c.field-meta.xml
<CustomField>
    <fullName>Coordinating_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coordinating Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements (Coordinating Office)</relationshipLabel>
    <relationshipName>Engagements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <formula>Client__r.Name &amp; &quot; - &quot; &amp;  Engagement_Name_Tag__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Display Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscribed_Offices__c/Subscribed_Offices__c.object-meta.xml
<CustomObject>
    <label>Subscribed Offices</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Subscribed Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscribed Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscribed_Offices__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscribed Office</relationshipLabel>
    <relationshipName>Subscribed_Office</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscribed_Offices__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Subscribed Office</relationshipLabel>
    <relationshipName>Subscribed_Office</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/Work_Record__c.object-meta.xml
<CustomObject>
    <label>Work Record</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Record__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Linked work records to an Individual will show the work record to the user in the portal. This creates a permanent relationship to the Individual separate from the Engagement.</description>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ace_FilesDao.cls
public with sharing class ace_FilesDao {

     
        public List<ace_File__c> saveAceFiles(List<ace_File__c> files){
            upsert files;
            return files;
        }

      public List<ace_File__c> fetchAceFilesVisibleToExternalAudiencesById(Set<Id> aceFileIds) {
          return [
              SELECT Id, Internal_Review_Status__c 
              FROM ace_File__c
              WHERE Internal_Review_Status__c = 'Approved' 
                AND Id IN :aceFileIds
          ];
      }

      public List<ace_File__c> fetchAceFilesAddedInWindowForNotification(DateTime lookbackLimit){
        return [SELECT Id, Engagement__c, Engagement__r.Name,  Engagement__r.Coordinating_Office__c,Engagement__r.Display_Name__c,  Individual__r.Name, Individual__c, CreatedBy.UserType, Work_Record__c, 
                        Subscribed_Office__c,Subscribed_Office__r.Account__c, Internal_Visibility__c
                FROM ace_File__c
                WHERE 
                ((Engagement__c != null AND Individual__c = null AND Work_Record__c = null )
                OR
                (Individual__c !=null AND Engagement__c = null AND Work_Record__c = null ))
                AND CreatedDate > :lookbackLimit
                ];

      }

      public List<ace_File__c> fetchVisibleFiles() {
        return [
              SELECT Id, File_Name__c, Shared_File_Name__c, File_Type__c, Upload_Date__c,
                     Uploaded_By__r.Name,  Engagement__c , Engagement__r.Display_Name__c
              FROM ace_File__c
              WHERE Uploaded_By__c != null AND Engagement__c != NULL
          ];
      }

      public List<ace_File__c> fetchFilesByEngagementId(Id engagementId) {
         // SELECT Id, File_Name__c, Shared_File_Name__c, File_Type__c, Upload_Date__c,
                    // Uploaded_By__r.Name, Work_Record__r.Name, Engagement__c
             // FROM ace_File__c
          return [
              SELECT Id, File_Name__c, Shared_File_Name__c, File_Type__c, Upload_Date__c,
                     Uploaded_By__r.Name,  Engagement__c
              FROM ace_File__c
              WHERE Engagement__c = :engagementId
          ];
      }

      public List<ClientDocumentCenterCtrl.EngagementSummary> fetchEngagementsWithFiles(Integer batchSize, Integer offset) {
          // List<AggregateResult> results = [SELECT Engagement__c engagementId, Engagement__r.Name engagementName FROM ace_File__c WHERE Engagement__c != NULLGROUP BY Engagement__c, Engagement__r.NameORDER BY Engagement__c
          List<AggregateResult> results = [
              SELECT Engagement__c engagementId
              FROM ace_File__c
              WHERE Engagement__c != NULL
              GROUP BY Engagement__c 
              ORDER BY Engagement__c
              LIMIT :batchSize
              OFFSET :offset
          ];
          
           Set<Id> engagementIds = new Set<Id>();
        for (AggregateResult ar : results) {
            if (ar.get('engagementId') != null)
                engagementIds.add((Id)ar.get('engagementId'));
        }
          Map<Id, Engagement__c> engMap = engagementIds.isEmpty() 
            ? new Map<Id, Engagement__c>() 
            : new Map<Id, Engagement__c>(
                [SELECT Id, Display_Name__c FROM Engagement__c WHERE Id IN :engagementIds]
              );

          List<ClientDocumentCenterCtrl.EngagementSummary> summaries = new List<ClientDocumentCenterCtrl.EngagementSummary>();
          for (AggregateResult ar : results) {
              Id eid = (Id)ar.get('engagementId');
              ClientDocumentCenterCtrl.EngagementSummary summary = new ClientDocumentCenterCtrl.EngagementSummary();
              summary.engagementId = String.valueOf(eid);
            summary.engagementName = (engMap.containsKey(eid) ? engMap.get(eid).Display_Name__c : null);
            summaries.add(summary);
          }
          return summaries;
      } 
  }