force-app/main/default/objects/ace_File__c/ace_File__c.object-meta.xml
<CustomObject>
    <description>Contains metadata associated to a file. This metadata persists even when the file itself is deleted.</description>
    <label>Shared File</label>
    <nameField>
        <displayFormat>af-{000000}</displayFormat>
        <label>File ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared Files</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ace_File__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>JIRA:AGMPB-249</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>A_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the Person Account individual</description>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shared Files</relationshipLabel>
    <relationshipName>Shared_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/OriginalEntityContentDocumentKey__c.field-meta.xml
<CustomField>
    <fullName>OriginalEntityContentDocumentKey__c</fullName>
    <description>The concatentation of of the content document Id that the shared file associates to as well as the original linked entity.  Used in querying for Shared files where the content document Id is known.  This is relevant when a file is initially uploaded to another object and needs to be reparented.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>OriginalEntityContentDocumentKey</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <displayFormat>ENG-{0000000000}</displayFormat>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/TA_CDL_CreateSharedFilesForDirectCDLS.cls
public with sharing class TA_CDL_CreateSharedFilesForDirectCDLS implements TriggerAction.afterInsert{

    @testVisible
    private ace_Files aFiles;

    @testVisible
    private Files files;


    @testVisible
    private Set<Id> deletes;
    @testVisible
    private List<ace_File__c> inserts;
    @testVisible
    private List<ContentDocumentLink> newCdls;

    private static final Integer CONCATENATED_KEY_LENGTH = 36;
    private static final Map<String, String> OBJECT_FIELD_RELATION_MAP = new Map<String, String>{
        'Engagement__c' => 'Engagement__c',
        'Account' => 'Individual__c'
    };

    public TA_CDL_CreateSharedFilesForDirectCDLS() {
        this.aFiles = new ace_Files();
        this.files = new Files();

        this.deletes = new Set<Id>();
        this.inserts = new List<ace_File__c>();
        this.newCdls = new List<ContentDocumentLink>();
    }

    public void afterInsert(List<ContentDocumentLink> newList){
        for(ContentDocumentLink cdl : newList){
            String relatedFieldString = getRelatedObjectField(cdl);
            if(relatedFieldString != null){
                this.inserts.add(makeSharedFileForRecord(cdl, relatedFieldString));
                this.deletes.add(cdl.Id);
            }
        }

        if(this.inserts.size() > 0){
            this.aFiles.saveNewFiles(inserts);
            this.newCdls = makeNewCdls(inserts);
            this.files.addNewContentDocumentLinks(newCdls);
            this.files.removeContentDocumentLinks(deletes);
        }
        
        System.debug('INSERTS'+JSON.serialize(this.inserts));
        System.debug('DELETES: '+JSON.serialize(this.deletes));
     
      
    }

    @testVisible 
    private List<ContentDocumentLink> makeNewCdls(List<ace_File__c> newSharedFileRecords){
        List<ContentDocumentLink> cdls = new List<ContentDocumentLink>();

        for(ace_File__c file : newSharedFileRecords){
            if(file.OriginalEntityContentDocumentKey__c.length() == CONCATENATED_KEY_LENGTH){

                Id linkedEntityId = file.Id;
                Id contentDocumentId =file.OriginalEntityContentDocumentKey__c.right(18);
                
                cdls.add(new ContentDocumentLink(LinkedEntityId = linkedEntityId, ContentDocumentId = contentDocumentId));
            }
        }
        
        return cdls;
    }

    private ace_file__c makeSharedFileForRecord(ContentDocumentLink cdl, String relatedField){
        ace_File__c aFile = new ace_File__c();
     
        aFile.put(relatedField, cdl.LinkedEntityId);
        aFile.OriginalEntityContentDocumentKey__c = String.valueOf(cdl.LinkedEntityId)+String.valueOf(cdl.ContentDocumentId);
     
        return aFile;
    }

    private string getRelatedObjectField(ContentDocumentLink cdl){
        return OBJECT_FIELD_RELATION_MAP.get(getLinkedEntityObjectType(cdl));
    }

    private String getLinkedEntityObjectType(ContentDocumentLink cdl){
        Id linkedId = cdl.LinkedEntityId;
        return linkedId.getSobjectType().toString();
    }
}