force-app/main/default/objects/ace_File__c/ace_File__c.object-meta.xml
<CustomObject>
    <description>Contains metadata associated to a file. This metadata persists even when the file itself is deleted.</description>
    <label>Shared File</label>
    <nameField>
        <displayFormat>af-{000000}</displayFormat>
        <label>File ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared Files</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ace_File__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>JIRA:AGMPB-249</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>A_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <description>JIRA:AGMPB-437</description>
    <encryptionScheme>None</encryptionScheme>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Internal_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Internal_Review_Status__c</fullName>
    <description>Describes the status of an Ace File prior to sharing it externally with customer users.</description>
    <label>Internal Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <displayFormat>ENG-{0000000000}</displayFormat>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ace_FilesTest.cls
@isTest
public class ace_FilesTest {

    @isTest
    private static void itShouldCallTheDao() {
        Stub fileDao = new Stub(ace_FilesDao.class);
        fileDao.setReturnValue('saveAceFiles', null);

        ace_Files files = new ace_Files();
        files.dao = (ace_FilesDao)fileDao.instance;

        Test.startTest();
        files.flagFilesAsInternallyUploaded(new Set<Id>{
            TestUtility.getFakeId(ace_File__c.SObjectType)
        });
        Test.stopTest();

        fileDao.assertInvoked('saveAceFiles');
    }

    @isTest
    private static void test_getVisibleFiles() {
        Stub fileDao = new Stub(ace_FilesDao.class);

        ace_File__c mockFile = new ace_File__c(
            Id = TestUtility.getFakeId(ace_File__c.SObjectType),
            File_Name__c = 'Mock File'
        );

        fileDao.setReturnValue('fetchVisibleFiles', new List<ace_File__c>{ mockFile });

        ace_Files files = new ace_Files((ace_FilesDao)fileDao.instance);

        Test.startTest();
        List<ace_File__c> result = files.getVisibleFiles();
        Test.stopTest();
        
        fileDao.assertInvoked('fetchVisibleFiles');
    }

    @isTest
    private static void test_getFilesByEngagementId() {
        Stub fileDao = new Stub(ace_FilesDao.class);

        Id fakeEngagementId = TestUtility.getFakeId(Engagement__c.SObjectType);
        ace_File__c mockFile = new ace_File__c(
            Id = TestUtility.getFakeId(ace_File__c.SObjectType),
            Engagement__c = fakeEngagementId
        );

        fileDao.setReturnValue('fetchFilesByEngagementId', new List<ace_File__c>{ mockFile });

        ace_Files files = new ace_Files((ace_FilesDao)fileDao.instance);

        Test.startTest();
        List<ace_File__c> result = files.getFilesByEngagementId(fakeEngagementId);
        Test.stopTest();
        
        fileDao.assertInvoked('fetchFilesByEngagementId');
    }

    @isTest
    private static void test_getEngagementsWithFiles() {
        Stub fileDao = new Stub(ace_FilesDao.class);

        ClientDocumentCenterCtrl.EngagementSummary mockSummary = new ClientDocumentCenterCtrl.EngagementSummary();
        mockSummary.engagementId = TestUtility.getFakeId(Engagement__c.SObjectType);
      //  mockSummary.engagementName = 'Test Engagement';

        fileDao.setReturnValue('fetchEngagementsWithFiles', new List<ClientDocumentCenterCtrl.EngagementSummary>{ mockSummary });

        ace_Files files = new ace_Files((ace_FilesDao)fileDao.instance);

        Test.startTest();
        List<ClientDocumentCenterCtrl.EngagementSummary> result = files.getEngagementsWithFiles(5,0);
        Test.stopTest();
        
        fileDao.assertInvoked('fetchEngagementsWithFiles');
    }

    @isTest
    private static void test_getAceFilesVisibleToExternalAudiences() {
        Stub fileDao = new Stub(ace_FilesDao.class);

        ace_File__c mockFile = new ace_File__c(
            Id = TestUtility.getFakeId(ace_File__c.SObjectType),
            Internal_Review_Status__c = 'Approved'
        );

        fileDao.setReturnValue('fetchAceFilesVisibleToExternalAudiencesById', new List<ace_File__c>{ mockFile });

        ace_Files files = new ace_Files((ace_FilesDao)fileDao.instance);

        Set<Id> mockIds = new Set<Id>{ TestUtility.getFakeId(ace_File__c.SObjectType) };

        Test.startTest();
        List<ace_File__c> result = files.getAceFilesVisibleToExternalAudiences(mockIds);
        Test.stopTest();
        
        fileDao.assertInvoked('fetchAceFilesVisibleToExternalAudiencesById');
    }
}