force-app/main/default/objects/ace_File__c/ace_File__c.object-meta.xml
<CustomObject>
    <description>Contains metadata associated to a file. This metadata persists even when the file itself is deleted.</description>
    <label>Shared File</label>
    <nameField>
        <displayFormat>af-{000000}</displayFormat>
        <label>File ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared Files</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ace_File__c/fields/Internal_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Internal_Review_Status__c</fullName>
    <description>Describes the status of an Ace File prior to sharing it externally with customer users.</description>
    <label>Internal Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Is_Internally_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Is_Internally_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifies when the file linked to a record was internally uploaded. This supports identifying how files should be shared and processes for removal of files from the system.</description>
    <label>Is Internally Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Uploaded_By__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who uploaded the file attached to this record?</description>
    <label>Uploaded By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UploadedFiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ace_Files.cls
public with sharing class ace_Files {

    @testVisible 
    private ace_FilesDao dao;

    public ace_Files() {
        this.dao = new ace_FilesDao();
    }

    public ace_Files(ace_FilesDao dao) {
        this.dao = dao;
    }
    
    public List<ace_File__c> saveNewFiles(List<ace_File__c> aFiles){
        return this.dao.saveAceFiles(aFiles);
    }

    public List<ace_File__c> getVisibleFiles() {
        return dao.fetchVisibleFiles();
    }

    public List<ace_File__c> getAceFilesAddedInWindowForNotification(Integer lookbackWindowInHours){
        DateTime lookbackLimit = DateTime.Now().addHours(lookbackWindowInHours * -1);

        return this.dao.fetchAceFilesAddedInWindowForNotification(lookbackLimit);
    }

    public List<ace_File__c> getAceFilesVisibleToExternalAudiences(Set<Id> aceFileIds){
        return this.dao.fetchAceFilesVisibleToExternalAudiencesById(aceFileIds); 
    }

    public void flagFilesAsInternallyUploaded(Set<Id> aceFileIds){
        List<ace_File__c> fileRecords = new List<ace_File__c>();
        for(Id fileRecordId : aceFileIds){
            fileRecords.add(new ace_File__c(
                Id=fileRecordId, 
                Is_Internally_Uploaded__c = true, 
                Internal_Review_Status__c='Pending',
                Uploaded_By__c = UserInfo.getUserId()
            ));    
        }
        this.dao.saveAceFiles(fileRecords);
    }

    public List<ace_File__c> getFilesByEngagementId(Id engagementId) {
        return dao.fetchFilesByEngagementId(engagementId);
    }

   public List<ClientDocumentCenterCtrl.EngagementSummary> getEngagementsWithFiles(Integer batchSize, Integer offset) {
        return dao.fetchEngagementsWithFiles(batchSize, offset);
    }
}