force-app/main/default/objects/ace_File__c/ace_File__c.object-meta.xml
<CustomObject>
    <description>Contains metadata associated to a file. This metadata persists even when the file itself is deleted.</description>
    <label>Shared File</label>
    <nameField>
        <displayFormat>af-{000000}</displayFormat>
        <label>File ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared Files</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ace_File__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>JIRA:AGMPB-249</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>A_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the Person Account individual</description>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shared Files</relationshipLabel>
    <relationshipName>Shared_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Work_Record__c.field-meta.xml
<CustomField>
    <fullName>Work_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Record</label>
    <referenceTo>Work_Record__c</referenceTo>
    <relationshipName>Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <displayFormat>ENG-{0000000000}</displayFormat>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Record__c/Work_Record__c.object-meta.xml
<CustomObject>
    <label>Work Record</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Record__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Linked work records to an Individual will show the work record to the user in the portal. This creates a permanent relationship to the Individual separate from the Engagement.</description>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FileNotificationAlertComposerTest.cls
@isTest 
public with sharing class FileNotificationAlertComposerTest {

    @isTest 
    private static void itShouldComposeTheEmailMessageWithEngagementsAndIndividuals(){

        Account individualAccount = new Account(Name='Person');
        String engagementString = new MobilityTestRecordBuilder()
                                        .withObjectType(Engagement__c.SObjectType)
                                        .withFields(new Map<String, String>{'Name'=>'Test'})
                                        .build()
                                        .getObjectString();

        String individualAccountString = JSON.serialize(individualAccount);
        String internalUserString = new MobilityTestRecordBuilder()
            .withObjectType(User.sObjectType)
            .withFields(new Map<String, String>{'UserType'=>'Standard'})
            .build()
            .getObjectString();
        String externalUserString = new MobilityTestRecordBuilder()
            .withObjectType(User.sObjectType)
            .withFields(new Map<String, String>{'UserType'=>'CustomerSuccess'})
            .build()
            .getObjectString();
        String internallyCreatedEngagementFileString = new MobilityTestRecordBuilder()
            .withObjectType(ace_File__c.SObjectType)
            .withFields(new Map<String, String>{'Work_Record__c'=>null, 'Individual__c'=>null, 'Engagement__c'=>TestUtility.getFakeId(Engagement__c.SObjectType)})
            .withParentRecords('Engagement__r', engagementString)
            .withParentRecords('CreatedBy', internalUserString)
            .build()
            .getObjectString();
        String externallyCreatedEngagementFileString = new MobilityTestRecordBuilder()
            .withObjectType(ace_File__c.SObjectType)
            .withParentRecords('Engagement__r', engagementString)
            .withFields(new Map<String, String>{'Work_Record__c'=>null, 'Individual__c'=>null, 'Engagement__c'=>TestUtility.getFakeId(Engagement__c.SObjectType)})
            .withParentRecords('CreatedBy', externalUserString)
            .build()
            .getObjectString();
        String externallyCreatedIndividualFileString = new MobilityTestRecordBuilder()
            .withObjectType(ace_File__c.SObjectType).withParentRecords('Individual__r', individualAccountString).withParentRecords('CreatedBy', externalUserString)
            .withFields(new Map<String, String>{'Work_Record__c'=>null, 'Individual__c'=>TestUtility.getFakeId(Account.SObjectType), 'Engagement__c'=>null})
            .build()
            .getObjectString();

        FileNotificationQueueEntry queueEntry = new FileNotificationQueueEntry(TestUtility.getFakeId(Group.SObjectType),(ace_File__c)JSON.deserialize(internallyCreatedEngagementFileString, ace_File__c.class));
        queueEntry.addFile((ace_File__c)JSON.deserialize(internallyCreatedEngagementFileString, ace_File__c.class));
        queueEntry.addFile((ace_File__c)JSON.deserialize(externallyCreatedEngagementFileString, ace_File__c.class));       
        queueEntry.addFile((ace_File__c)JSON.deserialize(externallyCreatedIndividualFileString, ace_File__c.class));
        queueEntry.addFile((ace_File__c)JSON.deserialize(externallyCreatedIndividualFileString, ace_File__c.class));
        queueEntry.addFile((ace_File__c)JSON.deserialize(externallyCreatedIndividualFileString, ace_File__c.class));
        
        System.debug(JSON.serialize(queueEntry));
        
        FileNotificationAlertComposer composer = new FileNotificationAlertComposer();
        String resultMessage;

        test.startTest();

        resultMessage = composer.getAlertMessage(queueEntry, 10);

        test.stopTest();


        System.assert(resultMessage.contains(FileNotificationAlertComposer.ALERT_INTRO));
        System.assert(resultMessage.contains(FileNotificationAlertComposer.ENGAGEMENT_HEADER));
        System.assert(resultMessage.contains(FileNotificationAlertComposer.INDIVIDUAL_HEADER));
        System.assert(resultMessage.contains(FileNotificationAlertComposer.ENGAGEMENT_FILES_INTERNAL));
        System.assert(resultMessage.contains(FileNotificationAlertComposer.ENGAGEMENT_FILES_EXTERNAL));
        System.assert(resultMessage.contains(FileNotificationAlertComposer.INDIVIDUAL_FILES_EXTERNAL));
        System.assert(resultMessage.contains(FileNotificationAlertComposer.INDIVIDUAL_FILES_INTERNAL));
    }

    @isTest 
    private static void itShouldNotIncludeIndividualHeaders(){
        String engagementString = new MobilityTestRecordBuilder()
                                        .withObjectType(Engagement__c.SObjectType)
                                        .withFields(new Map<String, String>{'Name'=>'Test'})
                                        .build()
                                        .getObjectString();

        String internalUserString = new MobilityTestRecordBuilder()
            .withObjectType(User.sObjectType)
            .withFields(new Map<String, String>{'UserType'=>'Standard'})
            .build()
            .getObjectString();
        String externalUserString = new MobilityTestRecordBuilder()
            .withObjectType(User.sObjectType)
            .withFields(new Map<String, String>{'UserType'=>'CustomerSuccess'})
            .build()
            .getObjectString();
        String internallyCreatedEngagementFileString = new MobilityTestRecordBuilder()
            .withObjectType(ace_File__c.SObjectType)
            .withFields(new Map<String, String>{'Work_Record__c'=>null, 'Individual__c'=>null, 'Engagement__c'=>TestUtility.getFakeId(Engagement__c.SObjectType)})
            .withParentRecords('Engagement__r', engagementString)
            .withParentRecords('CreatedBy', internalUserString)
            .build()
            .getObjectString();
        String externallyCreatedEngagementFileString = new MobilityTestRecordBuilder()
            .withObjectType(ace_File__c.SObjectType)
            .withParentRecords('Engagement__r', engagementString)
            .withFields(new Map<String, String>{'Work_Record__c'=>null, 'Individual__c'=>null, 'Engagement__c'=>TestUtility.getFakeId(Engagement__c.SObjectType)})
            .withParentRecords('CreatedBy', externalUserString)
            .build()
            .getObjectString();
       
        FileNotificationQueueEntry queueEntry = new FileNotificationQueueEntry(TestUtility.getFakeId(Group.SObjectType),(ace_File__c)JSON.deserialize(internallyCreatedEngagementFileString, ace_File__c.class));
        queueEntry.addFile((ace_File__c)JSON.deserialize(internallyCreatedEngagementFileString, ace_File__c.class));
        queueEntry.addFile((ace_File__c)JSON.deserialize(externallyCreatedEngagementFileString, ace_File__c.class));       
        
        System.debug(JSON.serialize(queueEntry));
        
        FileNotificationAlertComposer composer = new FileNotificationAlertComposer();
        String resultMessage;

        test.startTest();

        resultMessage = composer.getAlertMessage(queueEntry, 10);

        test.stopTest();

		System.debug('THE MESSAGE: '+resultMessage);
        
        System.assert(resultMessage.contains(FileNotificationAlertComposer.ALERT_INTRO), 'expect the result to contain '+FileNotificationAlertComposer.ALERT_INTRO);
        System.assert(resultMessage.contains(FileNotificationAlertComposer.ENGAGEMENT_HEADER), 'expect the result to contain '+FileNotificationAlertComposer.ENGAGEMENT_HEADER);
        System.assert(!resultMessage.contains(FileNotificationAlertComposer.INDIVIDUAL_HEADER), 'expect the result to NOT contain '+FileNotificationAlertComposer.INDIVIDUAL_HEADER);
        System.assert(resultMessage.contains(FileNotificationAlertComposer.ENGAGEMENT_FILES_INTERNAL),'expect the result to contain '+FileNotificationAlertComposer.ENGAGEMENT_FILES_INTERNAL);
        System.assert(resultMessage.contains(FileNotificationAlertComposer.ENGAGEMENT_FILES_EXTERNAL), 'expect the result to contain '+FileNotificationAlertComposer.ENGAGEMENT_FILES_EXTERNAL);
        System.assert(!resultMessage.contains(FileNotificationAlertComposer.INDIVIDUAL_FILES_EXTERNAL),'expect the result to NOT contain '+FileNotificationAlertComposer.INDIVIDUAL_FILES_EXTERNAL);
    }
}