force-app/main/default/objects/ace_File__c/ace_File__c.object-meta.xml
<CustomObject>
    <description>Contains metadata associated to a file. This metadata persists even when the file itself is deleted.</description>
    <label>Shared File</label>
    <nameField>
        <displayFormat>af-{000000}</displayFormat>
        <label>File ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared Files</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ace_File__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>JIRA:AGMPB-249</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>A_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Engagement_Assignee__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>JIRA:AGMPB-272</description>
    <label>Engagement Assignee</label>
    <referenceTo>Engagement_Assignee__c</referenceTo>
    <relationshipName>A_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the Person Account individual</description>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shared Files</relationshipLabel>
    <relationshipName>Shared_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Internal_Visibility__c.field-meta.xml
<CustomField>
    <fullName>Internal_Visibility__c</fullName>
    <description>Used by internal Andersen users to indicate who a Shared File record should be shared with.</description>
    <label>Internal Visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All Firms on Engagement</fullName>
            </value>
            <value>
                <fullName>Coordinating Country</fullName>
            </value>
            <value>
                <fullName>Country-Specific</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Subscribed_Office__c.field-meta.xml
<CustomField>
    <fullName>Subscribed_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the Shared File to a specific office, so the office can see it,.</description>
    <label>Subscribed Office</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>If there is an Engagement related to a Shared File, only Subscribed Office related to the same engagement can be added.</errorMessage>
        <filterItems>
            <field>$Source.Engagement__c</field>
            <operation>equals</operation>
            <valueField>Subscribed_Offices__c.Engagement__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Engagement__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscribed_Offices__c</referenceTo>
    <relationshipLabel>Shared Files</relationshipLabel>
    <relationshipName>Shared_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Work_Record__c.field-meta.xml
<CustomField>
    <fullName>Work_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Record</label>
    <referenceTo>Work_Record__c</referenceTo>
    <relationshipName>Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <displayFormat>ENG-{0000000000}</displayFormat>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Coordinating_Office__c.field-meta.xml
<CustomField>
    <fullName>Coordinating_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coordinating Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements (Coordinating Office)</relationshipLabel>
    <relationshipName>Engagements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/Engagement_Assignee__c.object-meta.xml
<CustomObject>
    <label>Mobile Employee</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Mobile Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobile Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Assignee__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mobile Employees</relationshipLabel>
    <relationshipName>Engagement_Assignees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/fields/Engagements__c.field-meta.xml
<CustomField>
    <fullName>Engagements__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Mobile Employees</relationshipLabel>
    <relationshipName>Engagement_Assignees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscribed_Offices__c/Subscribed_Offices__c.object-meta.xml
<CustomObject>
    <label>Subscribed Offices</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Subscribed Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscribed Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscribed_Offices__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscribed Office</relationshipLabel>
    <relationshipName>Subscribed_Office</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscribed_Offices__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Subscribed Office</relationshipLabel>
    <relationshipName>Subscribed_Office</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/Work_Record__c.object-meta.xml
<CustomObject>
    <label>Work Record</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Record__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/fields/Engagement_Assignee__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mobile Employee</label>
    <referenceTo>Engagement_Assignee__c</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Linked work records to an Individual will show the work record to the user in the portal. This creates a permanent relationship to the Individual separate from the Engagement.</description>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FileNotificationJobService.cls
public with sharing class FileNotificationJobService {

    private static final String INDIVIDUAL_KEY = 'Individual';
    private static final String ENGAGEMENT_KEY = 'Engagement';
    private static final String ALL_FIRMS_KEY = 'All Firms on Engagement'; //TODO.. make enum?
	
    @testVisible
    private ace_Files aFiles;
    @testVisible
    private Engagements engagements;
    @testVisible
    private Accounts accounts;

    @testVisible
    private Map<Id, Account> accountsById;
    @testVisible
    private Map<Id, Id> coordinatingOfficeByIndividual;
    @testVisible
    private Map<Id, List<Subscribed_Offices__c>> subscribedOfficesByEngagement;

    private List<ace_File__c> newFiles;
    
    public FileNotificationJobService() {
     	this.aFiles= new ace_Files();
        this.engagements = new Engagements();
        this.accounts = new Accounts();
    }

    public FileNotificationJob makeFileNotificationJob(Integer emailChunkSize, Integer lookbackWindow){
        initializeData(lookbackWindow);

        FileNotificationJob job = new FileNotificationJob(emailChunkSize, lookbackWindow);
        job.addItems(makeJobRequests());

        return job;
    }

    public Integer getFilesReviewedSize(){
        return this.newFiles.size();
    }

    @testVisible
    private void initializeData(Integer lookbackWindow){
        this.accountsById = new Map<Id, Account>();
        this.coordinatingOfficeByIndividual = new Map<Id, Id>();

        this.newfiles = getFilesSinceLookback(lookbackWindow);
        Map<String, Set<Id>> recordIdsByType = getRecordIdsBySharedFileType(this.newFiles);
        this.subscribedOfficesByEngagement = getSubscribedOfficesForEngagements(recordIdsByType.get(ENGAGEMENT_KEY)); 
        this.coordinatingOfficeByIndividual  = getCoordinatingCountriesForIndividualFiles(recordIdsByType.get(INDIVIDUAL_KEY));
       
        setAccountData();  
    }

    private void setAccountData(){
        Set<Id> firmAccountIds = new Set<Id>();
        firmAccountIds.addAll(getAccountIds(this.subscribedOfficesByEngagement.values()));
        firmAccountIds.addAll(this.coordinatingOfficeByIndividual.values());
        firmAccountIds.addAll(getCoordinatingOfficeFirmAccountsForEngagementFiles(this.newFiles));
        
        setAccountsById(firmAccountIds);
    }

    private List<ace_File__c> getFilesSinceLookback(Integer lookbackWindow){
        return this.aFiles.getAceFilesAddedInWindowForNotification(lookbackWindow);
    }

    private List<FileNotificationJob.Request> makeJobRequests(){
        List<FileNotificationJob.Request> requests = new List<FileNotificationJob.Request>();

        for(ace_File__c sharedFile : this.newFiles){
            requests.add(makeJobRequest(sharedFile));
        }

        return requests;
    }

    @testVisible
    private FileNotificationJob.Request makeJobRequest(ace_File__c sharedFile){
        FileNotificationJob.Request request = new FileNotificationJob.Request(sharedFile);
        Set<Account> offices = getOfficesForFile(sharedFile);
        
       
        request.addOffices(offices);

        return request;
    }

    private Set<Account> getOfficesForFile(ace_File__c sharedFile){
        Set<Account> offices = new Set<Account>();
        if(isEngagementFile(sharedFile)){
            offices = addOfficeAccount(offices, sharedFile.Engagement__r.Coordinating_Office__c);
        }
        if(isIndividualFile(sharedFile)){
           offices = addOfficeAccount(offices, this.coordinatingOfficeByIndividual.get(sharedFile.Individual__c));
        }
        if(hasSubscribedOffice((sharedFile))){
            offices = addOfficeAccount(offices, sharedFile.Subscribed_Office__r.Account__c);
        }
        if(isSharedWithAllOffices(sharedFile)){
            offices = addAllSubscribedOfficeAccounts(offices, sharedFile.Engagement__c);
        }
        
        return offices;
    }

    private Set<Account> addOfficeAccount(Set<Account> offices, Id officeAccountId){
        if(this.accountsById.containsKey(officeAccountId)){
            offices.add(accountsById.get(officeAccountId));
        }

        return offices;
    }

   private Set<Account> addAllSubscribedOfficeAccounts(Set<Account> offices, Id engagementId){
        List<Subscribed_Offices__c> subscribedOfficesOnEngagement = subscribedOfficesByEngagement.get(engagementId);
        
        if(subscribedOfficesOnEngagement == null || subscribedOfficesOnEngagement.isEmpty()) return offices;

        for(Subscribed_Offices__c subscribedOffice : subscribedOfficesOnEngagement){
            offices = addOfficeAccount(offices, subscribedOffice.Account__c);
        }

        return offices;
   }

    private void setAccountsById(Set<Id> firmAccountIds){
        this.accountsById = this.accounts.getFirmAccountsById(firmAccountIds);
    }

    private Map<String, Set<Id>> getRecordIdsBySharedFileType(List<ace_File__c> sharedFiles){
        Map<String, Set<Id>> recordIdsByType = new Map<String, Set<Id>>{INDIVIDUAL_KEY => new Set<Id>(), ENGAGEMENT_KEY=> new Set<Id>()};
        for(ace_File__c sharedFile : sharedFiles){
            if(isEngagementFile(sharedFile)){
                recordIdsByType.get(ENGAGEMENT_KEY).add(sharedFile.Engagement__c);
            }
            if(isIndividualFile(sharedFile)){
                recordIdsByType.get(INDIVIDUAL_KEY).add(sharedFile.Individual__c);
            }
        }

        return recordIdsByType;
    }

    private Map<Id, List<Subscribed_Offices__c>> getSubscribedOfficesForEngagements(Set<Id> engagementIds){
        Map<Id, List<Subscribed_Offices__c>> officesByEngagements = new Map<Id, List<Subscribed_Offices__c>>();
        for(Engagement__c engagement : this.engagements.getEngagementsWithAllSubscribedOffices(engagementIds).values()){
            officesByEngagements.put(engagement.Id, engagement.Subscribed_Office__r);
        }

        return officesByEngagements;
    }

    private Map<Id, Id> getCoordinatingCountriesForIndividualFiles(Set<Id> individualIds){
        Map<Id, Id> individualToCoordinatingCountryMap = new Map<Id, Id>();
        for(Engagement_Assignee__c employee : this.engagements.getMobileEmployeesByIndividualId(individualIds)){
            individualToCoordinatingCountryMap.put(employee.Assignee__c, employee.Engagements__r.Coordinating_Office__c);
        }

        return individualToCoordinatingCountryMap;
    }
    
    private Set<Id> getCoordinatingOfficeFirmAccountsForEngagementFiles(List<ace_File__c> sharedFiles){
        Set<Id> firmAccountIds = new Set<Id>();

        for(ace_File__c sharedFile : sharedFiles){
            firmAccountIds.add(sharedFile.Engagement__r.Coordinating_Office__c);
        }

        return firmAccountIds;
    }


    private Boolean isEngagementFile(ace_File__c sharedFile){
        return sharedFile.Engagement__c != null && sharedFile.Individual__c == null && sharedFile.Work_Record__c == null;
    }

    private Boolean isIndividualFile(ace_File__c sharedFile){
        return sharedFile.Individual__c != null && sharedFile.Engagement__c == null && sharedFile.Work_Record__c == null;
    }

    private boolean hasSubscribedOffice(ace_File__c sharedFile){
        return sharedFile.Subscribed_Office__c != null;
    }
    
    private Boolean isSharedWithAllOffices(ace_File__c sharedFile){
        return isEngagementFile(sharedFile) && sharedFile.Internal_Visibility__c != null && sharedFile.Internal_Visibility__c.equalsIgnoreCase(ALL_FIRMS_KEY);
    }

    private Set<Id> getAccountIds(List<List<Subscribed_Offices__c>> records){
        Set<Id> accountIds = new Set<Id>();
        
        for(List<Subscribed_Offices__c> officeList : records){
            for(Subscribed_Offices__c office : officeList){
                accountIds.add(office.Account__c);
            }
        }

        return accountIds;
    }
   
}