force-app/main/default/objects/ace_File__c/ace_File__c.object-meta.xml
<CustomObject>
    <description>Contains metadata associated to a file. This metadata persists even when the file itself is deleted.</description>
    <label>Shared File</label>
    <nameField>
        <displayFormat>af-{000000}</displayFormat>
        <label>File ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared Files</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ace_File__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>JIRA:AGMPB-249</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>A_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <description>JIRA:AGMPB-437</description>
    <encryptionScheme>None</encryptionScheme>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <description>JIRA:AGMPB-437</description>
    <encryptionScheme>None</encryptionScheme>
    <label>File Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Shared_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Shared_File_Name__c</fullName>
    <description>JIRA:AGMPB-774</description>
    <formula>HYPERLINK(
  LEFT(
    $Api.Partner_Server_URL_260,
    FIND(&apos;/services&apos;, $Api.Partner_Server_URL_260)
  ) &amp; &apos;/&apos; &amp; Id,
  IF(
    NOT(ISBLANK(File_Name__c)),
    File_Name__c &amp;
      IF(
        NOT(ISBLANK(File_Type__c)),
        &quot;.&quot; &amp; File_Type__c,
        Name
      ),
    Name
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shared File Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Upload_Date__c.field-meta.xml
<CustomField>
    <fullName>Upload_Date__c</fullName>
    <description>JIRA:AGMPB-437</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Upload Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Uploaded_By__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who uploaded the file attached to this record?</description>
    <label>Uploaded By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UploadedFiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Work_Record__c.field-meta.xml
<CustomField>
    <fullName>Work_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Record</label>
    <referenceTo>Work_Record__c</referenceTo>
    <relationshipName>Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <displayFormat>ENG-{0000000000}</displayFormat>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <formula>Client__r.Name &amp; &quot; - &quot; &amp;  Engagement_Name_Tag__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Display Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/Work_Record__c.object-meta.xml
<CustomObject>
    <label>Work Record</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Record__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ClientDocumentCenterCtrl.cls
public with sharing class ClientDocumentCenterCtrl {

    private static ace_Files fileService = new ace_Files(); 

    @TestVisible
    private static void setFileService(ace_Files mockService) {
        fileService = mockService;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<EngagementFileTreeWrapper> getVisibleFiles() {
        List<ace_File__c> files = fileService.getVisibleFiles();

        Map<Id, EngagementFileTreeWrapper> engagementMap = new Map<Id, EngagementFileTreeWrapper>();

        for (ace_File__c file : files) {
            if (!engagementMap.containsKey(file.Engagement__c)) {
                EngagementFileTreeWrapper wrapper = new EngagementFileTreeWrapper();
                wrapper.engagementId = file.Engagement__c;
                wrapper.engagementName = file.Engagement__r.Display_Name__c;
                wrapper.files = new List<FileNode>();
                engagementMap.put(file.Engagement__c, wrapper);
            }

            engagementMap.get(file.Engagement__c).files.add(buildFileNode(file));
        }

        return new List<EngagementFileTreeWrapper>(engagementMap.values());
    }

    @AuraEnabled(cacheable=true)
    public static List<FileNode> getEngagementFiles(Id engagementId) {
        ace_Files fileService = new ace_Files();
        List<ace_File__c> files = fileService.getFilesByEngagementId(engagementId);

        List<FileNode> result = new List<FileNode>();
        for (ace_File__c file : files) {
            result.add(buildFileNode(file));
        }

        return result;
    }

    private static FileNode buildFileNode(ace_File__c file) {
        FileNode node = new FileNode();
        node.fileId = file.Id;
        node.fileName = file.File_Name__c;
        node.sharedfileName = file.Shared_File_Name__c;
       // node.workRecordName = file.Work_Record__r != null ? file.Work_Record__r.Name : '';
        node.uploadedBy = file.Uploaded_By__r != null ? file.Uploaded_By__r.Name : '';
        node.uploadedDate = file.Upload_Date__c;
        node.fileType = file.File_Type__c;
        return node;
    }

    @AuraEnabled(cacheable=true)
    public static List<EngagementSummary> getEngagementsWithFiles(Integer batchSize, Integer offset) {
        ace_Files fileService = new ace_Files();
        return fileService.getEngagementsWithFiles(batchSize, offset);
    }

    public class EngagementFileTreeWrapper {
        @AuraEnabled public String engagementId;
        @AuraEnabled public String engagementName;
        @AuraEnabled public List<FileNode> files;
    }

    public class FileNode {
        @AuraEnabled public String fileId;
        @AuraEnabled public String fileName;
        @AuraEnabled public String sharedfileName;
        @AuraEnabled public String fileType;
        @AuraEnabled public String uploadedBy;
        @AuraEnabled public DateTime uploadedDate;
       @AuraEnabled public String workRecordName;
    }

    public class EngagementSummary {
        @AuraEnabled public String engagementId;
       @AuraEnabled public String engagementName;
    }
}