force-app/main/default/objects/ace_File__c/ace_File__c.object-meta.xml
<CustomObject>
    <description>Contains metadata associated to a file. This metadata persists even when the file itself is deleted.</description>
    <label>Shared File</label>
    <nameField>
        <displayFormat>af-{000000}</displayFormat>
        <label>File ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared Files</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ace_File__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>JIRA:AGMPB-249</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>A_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the Person Account individual</description>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shared Files</relationshipLabel>
    <relationshipName>Shared_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Work_Record__c.field-meta.xml
<CustomField>
    <fullName>Work_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Record</label>
    <referenceTo>Work_Record__c</referenceTo>
    <relationshipName>Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <displayFormat>ENG-{0000000000}</displayFormat>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Record__c/Work_Record__c.object-meta.xml
<CustomObject>
    <label>Work Record</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Record__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Linked work records to an Individual will show the work record to the user in the portal. This creates a permanent relationship to the Individual separate from the Engagement.</description>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FileNotificationQueueTest.cls
@isTest 
public with sharing class FileNotificationQueueTest {
    
    @isTest 
    private static void itShouldAddFiles(){
        Id groupId = TestUtility.getFakeId(Group.sObjectType);
        
        ace_File__c sharedFile = makeFakeSharedFile();
        
        FileNotificationQueue queue = new FileNotificationQueue();
        
        test.startTest();
        
        queue.addFile(sharedFile, groupId);
        queue.addFile(sharedFile, groupId);
        
        test.stopTest();
        
        System.assertEquals(true, queue.hasItems(), 'expect items in the queue!');
        System.assertEquals(1, queue.notificationQueueItems.keySet().size(), 'only one group, so should be only one queue');
    }
    
    @isTest
    private static void itShouldGetItems(){
        
        Id groupId = TestUtility.getFakeId(Group.sObjectType);
        ace_File__c sharedFile = makeFakeSharedFile();
        
        FileNotificationQueue queue = new FileNotificationQueue();
        FileNotificationQueueEntry entry;
        queue.addFile(sharedFile, groupId);
        queue.addFile(sharedFile, groupId);
        
        test.startTest();
        
        entry = queue.getNextQueueItem();
        
        test.stopTest();
        
        System.assertEquals(true, queue.hasItems(), 'expect items in the queue!');
        System.assertEquals(false, queue.hasMoreItems());
       	System.assert(entry != null, 'expected to get an entry back');
        System.assertEquals(0, queue.queueIndex, 'expected index to be at zero, after a single request');
    }
    
    @isTest
    private static void itShouldClearlyIndicateWhenOutOfItems(){
        Id groupId = TestUtility.getFakeId(Group.sObjectType);
        ace_File__c sharedFile = makeFakeSharedFile();
        
        FileNotificationQueue queue = new FileNotificationQueue();
        queue.addFile(sharedFile, groupId);
        queue.addFile(sharedFile, TestUtility.getFakeId(Group.sObjectType));
        queue.addFile(sharedFile, TestUtility.getFakeId(Group.sObjectType));
        
        
        test.startTest();
		
        for(Integer i = 0; i<4; i++){
            if(queue.hasMoreItems()){
                FileNotificationQueueEntry queueEntry = queue.getNextQueueItem();
            } else {
                continue;
            }
        }
        
        test.stopTest();
        
        System.assertEquals(false, queue.hasMoreItems(), 'expect false!');
        System.assertEquals(2, queue.queueIndex, 'expect index to be on last row');
    }
    
    @isTest
    private static void itShouldReturnTheQueueAsList(){
       
        Id groupId = TestUtility.getFakeId(Group.sObjectType);
        ace_File__c sharedFile = makeFakeSharedFile();
        
        FileNotificationQueue queue = new FileNotificationQueue();
        queue.addFile(sharedFile, groupId);
        queue.addFile(sharedFile, groupId);
        
        List<FileNotificationQueueEntry> queueEntries;
        
        test.startTest();
        
        queueEntries = queue.getQueue();       
        
        test.stopTest();
		
		System.assertEquals(1, queueEntries.size());        
    }
    
    private static ace_File__c makeFakeSharedFile(){
        String userString = new MobilityTestRecordBuilder()
            .withObjectType(User.sObjectType)
            .withFields(new Map<String, String>{'UserType'=>'Standard'})
            .build()
            .getObjectString();
        String engagementString = new MobilityTestRecordBuilder()
            .withObjectType(Engagement__c.SObjectType)
            .withFields(new Map<String, String>{'Name'=>'Super Engagement'})
            .build()
            .getObjectString();
        String sharedFileString = new MobilityTestRecordBuilder()
            .withObjectType(ace_File__c.sObjectType)
            .withParentRecords('CreatedBy', userString)
            .withParentRecords('Engagement__r', engagementString)
            .withFields(new Map<String, String>{'Engagement__c'=>TestUtility.getFakeId(Engagement__c.sObjectType), 'Work_Record__c'=>null, 'Individual__c'=>null})
            .build()
            .getObjectString();
        
        Id groupId = TestUtility.getFakeId(Group.sObjectType);
        ace_File__c sharedFile = (ace_File__c)JSON.deserialize(sharedFileString, ace_File__c.class);
        
        return sharedFile;
    }
}