force-app/main/default/objects/ace_File__c/ace_File__c.object-meta.xml
<CustomObject>
    <description>Contains metadata associated to a file. This metadata persists even when the file itself is deleted.</description>
    <label>Shared File</label>
    <nameField>
        <displayFormat>af-{000000}</displayFormat>
        <label>File ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared Files</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ace_File__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>JIRA:AGMPB-249</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>A_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the Person Account individual</description>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shared Files</relationshipLabel>
    <relationshipName>Shared_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Work_Record__c.field-meta.xml
<CustomField>
    <fullName>Work_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Record</label>
    <referenceTo>Work_Record__c</referenceTo>
    <relationshipName>Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <displayFormat>ENG-{0000000000}</displayFormat>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Record__c/Work_Record__c.object-meta.xml
<CustomObject>
    <label>Work Record</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Record__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Linked work records to an Individual will show the work record to the user in the portal. This creates a permanent relationship to the Individual separate from the Engagement.</description>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FileNotificationQueueEntryTest.cls
@isTest 
public with sharing class FileNotificationQueueEntryTest {
    
    @isTest 
    public static void isShouldAddEngagementfiles() {
            String userString = new MobilityTestRecordBuilder()
                .withObjectType(User.sObjectType)
                .withFields(new Map<String, String>{'UserType'=>'Standard'})
                .build()
                .getObjectString();
            String engagementString = new MobilityTestRecordBuilder()
                .withObjectType(Engagement__c.SObjectType)
                .withFields(new Map<String, String>{'Name'=>'Super Engagement'})
                .build()
                .getObjectString();
            String sharedFileString = new MobilityTestRecordBuilder()
                .withObjectType(ace_File__c.sObjectType)
                .withParentRecords('CreatedBy', userString)
                .withParentRecords('Engagement__r', engagementString)
                .withFields(new Map<String, String>{'Engagement__c'=>TestUtility.getFakeId(Engagement__c.sObjectType), 'Work_Record__c'=>null, 'Individual__c'=>null})
                .build()
                .getObjectString();

            ace_File__c sharedFile = (ace_File__c)JSON.deserialize(sharedFileString, ace_File__c.class);

            FileNotificationQueueEntry queueEntry;

        test.startTest();

        queueEntry = new FileNotificationQueueEntry(TestUtility.getFakeId(Group.SObjectType), sharedFile);
        test.stopTest();

        System.assertEquals(1, queueEntry.engagementFiles.keySet().size(), 'expect to see one file here');

    }

    @isTest 
    public static void isShouldAddIndividualfiles() {
    String userString = new MobilityTestRecordBuilder()
                .withObjectType(User.sObjectType)
                .withFields(new Map<String, String>{'UserType'=>'Standard'})
                .build()
                .getObjectString();
            String accountString = new MobilityTestRecordBuilder()
                .withObjectType(Account.SObjectType)
                .withFields(new Map<String, String>{'Name'=>'Super Person'})
                .build()
                .getObjectString();
            String sharedFileString = new MobilityTestRecordBuilder()
                .withObjectType(ace_File__c.sObjectType)
                .withParentRecords('CreatedBy', userString)
                .withParentRecords('Individual__r', accountString)
                .withFields(new Map<String, String>{'Engagement__c'=>null, 'Work_Record__c'=>null, 'Individual__c'=>TestUtility.getFakeId(Account.SObjectType)})
                .build()
                .getObjectString();

            ace_File__c sharedFile = (ace_File__c)JSON.deserialize(sharedFileString, ace_File__c.class);

            FileNotificationQueueEntry queueEntry;

        test.startTest();

        queueEntry = new FileNotificationQueueEntry(TestUtility.getFakeId(Group.SObjectType), sharedFile);
        
        test.stopTest();

        System.assertEquals(1, queueEntry.individualFiles.keySet().size(), 'expect to see one file here');
    }

     @isTest 
    public static void isShouldDoNothing() {
            String userString = new MobilityTestRecordBuilder()
                .withObjectType(User.sObjectType)
                .withFields(new Map<String, String>{'UserType'=>'Standard'})
                .build()
                .getObjectString();
            String engagementString = new MobilityTestRecordBuilder()
                .withObjectType(Engagement__c.SObjectType)
                .withFields(new Map<String, String>{'Name'=>'Super Engagement'})
                .build()
                .getObjectString();
            String sharedFileString = new MobilityTestRecordBuilder()
                .withObjectType(ace_File__c.sObjectType)
                .withParentRecords('CreatedBy', userString)
                .withParentRecords('Engagement__r', engagementString)
                .withFields(new Map<String, String>{'Engagement__c'=>TestUtility.getFakeId(Engagement__c.sObjectType), 'Work_Record__c'=>TestUtility.getFakeId(Work_Record__c.sObjectType), 'Individual__c'=>null})
                .build()
                .getObjectString();

         ace_File__c sharedFile = (ace_File__c)JSON.deserialize(sharedFileString, ace_File__c.class);

        FileNotificationQueueEntry queueEntry;

        test.startTest();

        queueEntry = new FileNotificationQueueEntry(TestUtility.getFakeId(Group.SObjectType), sharedFile);

        test.stopTest();

        System.assertEquals(0, queueEntry.individualFiles.keySet().size(), 'should not map into the individual files bucket');
        System.assertEquals(0, queueEntry.engagementFiles.keySet().size(), 'should not map into the engagement files bucket');
    }
    
}