force-app/main/default/objects/Account/fields/Global_Relationship_Director_Manager__c.field-meta.xml
<CustomField>
    <fullName>Global_Relationship_Director_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Relationship Director/Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Global_Relationship_Partner__c.field-meta.xml
<CustomField>
    <fullName>Global_Relationship_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Relationship Partner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Target</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not contracted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>A prospective, active or former corporate client</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contact/fields/LinkedIn_URL__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_URL__c</fullName>
    <description>This field used to store Linked URL of User.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>LinkedIn URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Client_Contact.recordType-meta.xml
<RecordType>
    <fullName>Client_Contact</fullName>
    <active>true</active>
    <label>Client Contact</label>
</RecordType>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <displayFormat>ENG-{0000000000}</displayFormat>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement_Name_Tag__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Name_Tag__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Engagement Name Tag</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Global_Relationship_Director_Manager__c.field-meta.xml
<CustomField>
    <fullName>Global_Relationship_Director_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Relationship Director/Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Engagements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Global_Relationship_Partner__c.field-meta.xml
<CustomField>
    <fullName>Global_Relationship_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Relationship Partner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Target</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not Contracted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/Engagement_Assignee__c.object-meta.xml
<CustomObject>
    <label>Mobile Employee</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Mobile Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobile Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Assignee__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mobile Employees</relationshipLabel>
    <relationshipName>Engagement_Assignees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/fields/Engagements__c.field-meta.xml
<CustomField>
    <fullName>Engagements__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Mobile Employees</relationshipLabel>
    <relationshipName>Engagement_Assignees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Awaiting Andersen Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>false</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/objects/User/fields/Country_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Service__c</fullName>
    <description>JIRA:AGMPB-297</description>
    <label>Country Contact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/LinkedIn_URL__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_URL__c</fullName>
    <description>JIRA:AGMPB-249</description>
    <encryptionScheme>None</encryptionScheme>
    <label>LinkedIn URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/Work_Record__c.object-meta.xml
<CustomObject>
    <label>Work Record</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Record__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/fields/Engagement_Assignee__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mobile Employee</label>
    <referenceTo>Engagement_Assignee__c</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Linked work records to an Individual will show the work record to the user in the portal. This creates a permanent relationship to the Individual separate from the Engagement.</description>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/fields/Net_Amount_in_Pocket__c.field-meta.xml
<CustomField>
    <fullName>Net_Amount_in_Pocket__c</fullName>
    <description>JIRA:AGMPB-312</description>
    <label>Net Amount in Pocket</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Non-Responder</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Record__c/fields/Work_Record_Contact__c.field-meta.xml
<CustomField>
    <fullName>Work_Record_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Record Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Internal Andersen User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/recordTypes/Consultation.recordType-meta.xml
<RecordType>
    <fullName>Consultation</fullName>
    <active>true</active>
    <label>Consultation</label>
</RecordType>

force-app/main/default/classes/ContactUserTableControllerTest.cls
@IsTest(SeeAllData=false)
public class ContactUserTableControllerTest {
    
    @IsTest
    static void testGetTopUsers() {
        Id personAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Account personAccount = new Account(
            FirstName = 'Test',
            LastName = 'Acc',
            RecordTypeId = personAccRecordTypeId
        );
        insert personAccount;
        
        Account testAccount = [SELECT Id, IsPersonAccount, PersonContactId FROM Account WHERE Id = :personAccount.Id];
        System.assertEquals(true, testAccount.IsPersonAccount);
        
      
        Id clientAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
        Account clientTestAccount = new Account(
            Name = 'Client Test Account',
            RecordTypeId = clientAccRecordTypeId,
            BillingStreet = '123 Street',
            BillingCity = 'TestCity',
            BillingPostalCode = '12345',
            BillingState = 'California',
            BillingCountry = 'United States'
        );
        insert clientTestAccount;
        
        Engagement__c testEngagement = new Engagement__c(
            Client__c = clientTestAccount.Id,
            Engagement_Name_Tag__c = 'Test'
        );
        insert testEngagement;
        
        Engagement_Assignee__c testEngagementAssignee = new Engagement_Assignee__c(
            First_Name__c = 'Test',
            Last_Name__c = 'Assignee',
            Assignee__c = testAccount.Id,
            Engagements__c = testEngagement.Id
        );
        insert testEngagementAssignee;
        
        Id contRecordTypeId1 = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Client_Contact').getRecordTypeId();
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'testcontact@example.com',
            RecordTypeId = contRecordTypeId1,
            AccountId = clientTestAccount.Id
        );
        insert testContact;
        
        Id workRecordTypeId = Schema.SObjectType.Work_Record__c.getRecordTypeInfosByName().get('Tax Return').getRecordTypeId();
        Work_Record__c workRecord1 = new Work_Record__c(
            Individual__c = testAccount.Id,
            Work_Record_Contact__c = null,
            Status__c = 'Active',
            RecordTypeId = workRecordTypeId,
            Net_Amount_in_Pocket__c =23,
            Country__c = 'USA',
            Engagement_Assignee__c = testEngagementAssignee.Id
        );
        Work_Record__c workRecord2 = new Work_Record__c(
            Individual__c = testAccount.Id,
            Work_Record_Contact__c = null,
            Status__c = 'Active',
            RecordTypeId = workRecordTypeId,
            Net_Amount_in_Pocket__c =09,
            Country__c = 'USA',
            Engagement_Assignee__c = testEngagementAssignee.Id
        );
        insert new List<Work_Record__c>{ workRecord1, workRecord2 };
            
        Id workRecordTypeId2 = Schema.SObjectType.Work_Record__c.getRecordTypeInfosByName().get('Certificate of Coverage').getRecordTypeId();
        Work_Record__c workRecord3 = new Work_Record__c(
            Individual__c = testAccount.Id,
            Work_Record_Contact__c = null,
            Status__c = 'Active',
            RecordTypeId = workRecordTypeId2,
            Country__c = 'USA',
            Net_Amount_in_Pocket__c =10,
            Engagement_Assignee__c = testEngagementAssignee.Id
        );
        Work_Record__c workRecord4 = new Work_Record__c(
            Individual__c = testAccount.Id,
            Work_Record_Contact__c = null,
            Status__c = 'Active',
            RecordTypeId = workRecordTypeId2,
            Net_Amount_in_Pocket__c =10,
            Country__c = 'USA',
            Engagement_Assignee__c = testEngagementAssignee.Id
        );
        insert new List<Work_Record__c>{ workRecord3, workRecord4 };
        
        Profile portalProfile = [SELECT Id FROM Profile WHERE Name = 'Assignee Portal' LIMIT 1];
        Profile internalUserProfile = [SELECT Id FROM Profile WHERE Name = 'Internal Andersen User' LIMIT 1];
        
        List<User> listOfUsers = new List<User>();
        
        User internalUser1 = new User(
            FirstName = 'Test',
            LastName = 'User1',
            Alias = 'tuser1',
            Email = 'testuser1' + DateTime.now().getTime() + '@example.com',
            Username = 'testuser1' + DateTime.now().getTime() + '@example.com',
            ProfileId = internalUserProfile.Id,
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            Country_of_Service__c = 'USA',
            LinkedIn_URL__c = 'https://www.linkedin.com/in/testuser1'
        );
        listOfUsers.add(internalUser1);
        
        User internalUser2 = new User(
            FirstName = 'Test',
            LastName = 'User2',
            Alias = 'tuser2',
            Email = 'testuser2' + DateTime.now().getTime() + '@example.com',
            Username = 'testuser2' + DateTime.now().getTime() + '@example.com',
            ProfileId = internalUserProfile.Id,
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            Country_of_Service__c = 'URY',
            LinkedIn_URL__c = 'https://www.linkedin.com/in/testuser2'
        );
        listOfUsers.add(internalUser2);
        
        User portalUser = new User(
            FirstName = 'Test',
            LastName = 'Portal',
            Alias = 'tportal',
            Email = 'portaluser' + DateTime.now().getTime() + '@example.com',
            Username = 'portaluser' + DateTime.now().getTime() + '@example.com',
            ProfileId = portalProfile.Id,
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            ContactId = testAccount.PersonContactId,
            LinkedIn_URL__c = 'https://www.linkedin.com/in/portaluser'
        );
        listOfUsers.add(portalUser);
        insert listOfUsers;
        
        workRecord1.Work_Record_Contact__c = internalUser1.Id;
        workRecord2.Work_Record_Contact__c = internalUser2.Id;
        update new List<Work_Record__c>{ workRecord1, workRecord2 };
        
        User queriedPortalUser = [SELECT Id, AccountId, ContactId FROM User WHERE Id = :portalUser.Id];
        
        System.runAs(portalUser) {
            Test.startTest();
            List<contactuserTableController.UserWrapper> users = contactuserTableController.getTopUsers(2);
            Test.stopTest();
            
            if(queriedPortalUser.AccountId == null) {
                System.assertEquals(0, users.size(), 'Expected 0 users because portalUser.AccountId is null in test context.');
            } else {
                System.assertNotEquals(null, users[0].Email, 'Email should not be null');
                System.assertNotEquals(null, users[0].ProfilePhoto, 'ProfilePhoto should not be null');
            }
        }
    }
    
    @IsTest
    static void testGetUsers() {
        Profile internalUserProfile = [SELECT Id FROM Profile WHERE Name = 'Internal Andersen User' LIMIT 1];
        User testUser = new User(
            FirstName = 'Test',
            LastName = 'User',
            Alias = 'tuser',
            Email = 'testuser' + DateTime.now().getTime() + '@example.com',
            Username = 'testuser' + DateTime.now().getTime() + '@example.com',
            ProfileId = internalUserProfile.Id,
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LinkedIn_URL__c = 'https://www.linkedin.com/in/testuser'
        );
        insert testUser;
        
        Test.startTest();
        List<contactuserTableController.UserWrapper> users = contactuserTableController.getUsers(testUser.Id,1,'Tax Return','USA');
        List<contactuserTableController.UserWrapper> users1 = contactuserTableController.getUsers(testUser.Id,1,'Certificate of Coverage','USA');
        List<contactuserTableController.UserWrapper> users2 = contactuserTableController.getUsers(testUser.Id,1,'Consultation','USA');
        Test.stopTest();
        
        System.assertEquals(1, users.size(), 'Expected one user returned by getUsers');
        System.assertEquals('Test User', users[0].Name, 'Expected user name to match');
    }
    
    @IsTest
    static void testGetEngagementUsers() {
        Profile clientProfile = [SELECT Id FROM Profile WHERE Name = 'Client Portal' LIMIT 1];
        Id clientAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
        Account clientAccount = new Account(
            Name = 'Client Account',
            RecordTypeId = clientAccRecordTypeId,
            BillingStreet = '123 William Street',
            BillingCity = 'New York',
            BillingPostalCode = '10038',
            BillingState = 'New York',
            BillingStateCode = 'NY',
            BillingCountryCode = 'US',
            BillingCountry = 'United States'
        );
        insert clientAccount;
        
        Id contRecordTypeId1 = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Client_Contact').getRecordTypeId();
        Contact clientContact = new Contact(
            AccountId = clientAccount.Id,
            FirstName='Testraj',
            LastName = 'ClientContact',
            RecordTypeId = contRecordTypeId1
        );
        insert clientContact;
        
        User clientUser = new User(
            Alias = 'client',
            Email = 'client' + DateTime.now().getTime() + '@test.com',
            EmailEncodingKey = 'UTF-8',
            FirstName='Testraj',
            LastName = 'Client',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = clientProfile.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            Username = 'client' + DateTime.now().getTime() + '@test.com',
            ContactId = clientContact.Id,
            LinkedIn_URL__c = 'https://www.linkedin.com/in/client'
        );
        insert clientUser;
        
        Engagement__c engagement = new Engagement__c(
            Client__c = clientAccount.Id,
            Engagement_Name_Tag__c = 'Test 2'
        );
        insert engagement;
        
        Profile internalUserProfile = [SELECT Id FROM Profile WHERE Name = 'Internal Andersen User' LIMIT 1];
        User testUser1 = new User(
            FirstName = 'John',
            LastName = 'Doe',
            Email = 'johndoe' + DateTime.now().getTime() + '@example.com',
            Username = 'johndoe' + DateTime.now().getTime() + '@example.com',
            Alias = 'jdoe',
            ProfileId = internalUserProfile.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LinkedIn_URL__c = 'https://www.linkedin.com/in/johndoe'
        );
        insert testUser1;
        
        User testUser2 = new User(
            FirstName = 'Jane',
            LastName = 'Smith',
            Email = 'janesmith' + DateTime.now().getTime() + '@example.com',
            Username = 'janesmith' + DateTime.now().getTime() + '@example.com',
            Alias = 'jsmith',
            ProfileId = internalUserProfile.Id,
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LinkedIn_URL__c = 'https://www.linkedin.com/in/janesmith'
        );
        insert testUser2;
        
        engagement.Global_Relationship_Director_Manager__c = testUser1.Id;
        engagement.Global_Relationship_Partner__c = testUser2.Id;
        update engagement;
        
        System.runAs(clientUser) {
            Test.startTest();
            List<contactuserTableController.UserWrapper> users = contactuserTableController.getEngagementUsers();
            Test.stopTest();
            
            System.assertEquals(2, users.size(), 'Expected 2 engagement users');
        }
    }
}