force-app/main/default/objects/Account/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.Firm_Type__c</field>
            <operation>equals</operation>
            <value>Member</value>
        </filterItems>
        <filterItems>
            <field>Account.Firm_Type__c</field>
            <operation>equals</operation>
            <value>Collaborating</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Partner Account)</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/RelatedGroupId__c.field-meta.xml
<CustomField>
    <fullName>RelatedGroupId__c</fullName>
    <description>Stores the ID of the related public group for the Firm account.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>RelatedGroupId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ace_File__c/ace_File__c.object-meta.xml
<CustomObject>
    <description>Contains metadata associated to a file. This metadata persists even when the file itself is deleted.</description>
    <label>Shared File</label>
    <nameField>
        <displayFormat>af-{000000}</displayFormat>
        <label>File ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared Files</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ace_File__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>JIRA:AGMPB-249</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>A_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Engagement_Assignee__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>JIRA:AGMPB-272</description>
    <label>Engagement Assignee</label>
    <referenceTo>Engagement_Assignee__c</referenceTo>
    <relationshipName>A_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the Person Account individual</description>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shared Files</relationshipLabel>
    <relationshipName>Shared_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Internal_Visibility__c.field-meta.xml
<CustomField>
    <fullName>Internal_Visibility__c</fullName>
    <description>Used by internal Andersen users to indicate who a Shared File record should be shared with.</description>
    <label>Internal Visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All Firms on Engagement</fullName>
            </value>
            <value>
                <fullName>Coordinating Country</fullName>
            </value>
            <value>
                <fullName>Country-Specific</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Subscribed_Office__c.field-meta.xml
<CustomField>
    <fullName>Subscribed_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the Shared File to a specific office, so the office can see it,.</description>
    <label>Subscribed Office</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>If there is an Engagement related to a Shared File, only Subscribed Office related to the same engagement can be added.</errorMessage>
        <filterItems>
            <field>$Source.Engagement__c</field>
            <operation>equals</operation>
            <valueField>Subscribed_Offices__c.Engagement__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Engagement__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Subscribed_Offices__c</referenceTo>
    <relationshipLabel>Shared Files</relationshipLabel>
    <relationshipName>Shared_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ace_File__c/fields/Work_Record__c.field-meta.xml
<CustomField>
    <fullName>Work_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Record</label>
    <referenceTo>Work_Record__c</referenceTo>
    <relationshipName>Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <displayFormat>ENG-{0000000000}</displayFormat>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Coordinating_Office__c.field-meta.xml
<CustomField>
    <fullName>Coordinating_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coordinating Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements (Coordinating Office)</relationshipLabel>
    <relationshipName>Engagements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Global_Relationship_Partner__c.field-meta.xml
<CustomField>
    <fullName>Global_Relationship_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Relationship Partner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/Engagement_Assignee__c.object-meta.xml
<CustomObject>
    <label>Mobile Employee</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Mobile Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobile Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Assignee__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mobile Employees</relationshipLabel>
    <relationshipName>Engagement_Assignees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/fields/Engagements__c.field-meta.xml
<CustomField>
    <fullName>Engagements__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Mobile Employees</relationshipLabel>
    <relationshipName>Engagement_Assignees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>false</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/objects/Subscribed_Offices__c/Subscribed_Offices__c.object-meta.xml
<CustomObject>
    <label>Subscribed Offices</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Subscribed Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscribed Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscribed_Offices__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscribed Office</relationshipLabel>
    <relationshipName>Subscribed_Office</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscribed_Offices__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Subscribed Office</relationshipLabel>
    <relationshipName>Subscribed_Office</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/Work_Record__c.object-meta.xml
<CustomObject>
    <label>Work Record</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Record__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/fields/Engagement_Assignee__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mobile Employee</label>
    <referenceTo>Engagement_Assignee__c</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Linked work records to an Individual will show the work record to the user in the portal. This creates a permanent relationship to the Individual separate from the Engagement.</description>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FileNotificationJobServiceTest.cls
@isTest 
public with sharing class FileNotificationJobServiceTest {
  
    @isTest
    private static void itShouldBePreparedToNotifyAllFirms(){
        Stub aFilesStub = new Stub(ace_Files.class);
		Stub engagementsStub = new Stub(Engagements.class);
		Stub accountStub = new Stub(Accounts.class);
        
        Account clientAccount = makeAccount();
        Account coordinatingAccount = makeAccount();
        Account subscribedOfficeAccount = makeAccount();
        Account personAccount = makeAccount();
        
		List<Account> officeAccounts = new List<Account>();
        officeAccounts.add(makeAccount());
        officeAccounts.add(makeAccount());
        officeAccounts.add(makeAccount());
        officeAccounts.add(makeAccount());
        officeAccounts.add(makeAccount());
        
        List<Account> returnedAccounts = new List<Account>{clientAccount, coordinatingAccount, subscribedOfficeAccount};
        
		returnedAccounts.addAll(officeAccounts);
            
        Engagement__c engagement = makeEngagement(clientAccount, coordinatingAccount);
        
        Subscribed_Offices__c subscribedOffice = makeSubscribedOffice(engagement, subscribedOfficeAccount);
        
        List<Subscribed_Offices__c> offices = new List<Subscribed_Offices__c>();
        offices.add(subscribedOffice);
        
        System.debug('SUB OFFICE: '+JSON.serialize(subscribedOffice));
        
        for(Account officeAccount : officeAccounts){
            offices.add(makeSubscribedOffice(engagement, officeAccount));
        }
        
        engagement = makeEngagementWithOffices(engagement, offices);
        
        Engagement_Assignee__c assignee = makeEngagementAssignee(engagement, personAccount);
        
        List<ace_File__c> filesSinceLookback = new List<ace_File__c>();
        ace_File__c highlyVisibleEngagementFile = makeEngagementFile(engagement, subscribedOffice);
        highlyVisibleEngagementFile.Internal_Visibility__c = 'All Firms on Engagement';
       
        ace_File__c lessVisibleEngagementFile = makeEngagementFile(engagement, subscribedOffice);
        
        //sub office should see 3 files.. everyone else should see one, except coordinating office.
        filesSinceLookback.add(lessVisibleEngagementFile);
        filesSinceLookback.add(highlyVisibleEngagementFile);
        filesSinceLookback.add(makeIndividualFile(personAccount, subscribedOffice));
        
		System.debug('files returned:: '+JSON.serialize(filesSinceLookback));
        
        aFilesStub.setReturnValue('getAceFilesAddedInWindowForNotification', filesSinceLookback);
        engagementsStub.setReturnValue('getEngagementsWithAllSubscribedOffices', new Map<Id, Engagement__c>{engagement.Id=>engagement});
        engagementsStub.setReturnValue('getMobileEmployeesByIndividualId', new List<Engagement_Assignee__c>{assignee});
        accountStub.setReturnValue('getFirmAccountsById', new Map<Id, Account>(returnedAccounts));
        
        FileNotificationJobService jobService = new FileNotificationJobService();
        jobService.aFiles = (ace_Files)aFilesStub.instance;
        jobService.engagements = (Engagements)engagementsStub.instance;
        jobService.accounts = (Accounts)accountStub.instance;
        
        FileNotificationJob job;
       
        test.startTest();
        
        job = jobService.makeFileNotificationJob(10,10);
        
        test.stopTest();
        
        
        System.debug(JSON.serialize(job));

    }


    @isTest 
    private static void itShouldDoTheThing(){
        Stub aFilesStub = new Stub(ace_Files.class);
		Stub engagementsStub = new Stub(Engagements.class);
		Stub accountStub = new Stub(Accounts.class);
        
        Account clientAccount = makeAccount();
        Account coordinatingAccount = makeAccount();
        Account subscribedOfficeAccount = makeAccount();
        Account personAccount = makeAccount();
        
        List<Account> returnedAccounts = new List<Account>{clientAccount, coordinatingAccount, subscribedOfficeAccount};
            
        Engagement__c engagement = makeEngagement(clientAccount, coordinatingAccount);
        Subscribed_Offices__c subscribedOffice = makeSubscribedOffice(engagement, subscribedOfficeAccount);
        
        engagement = makeEngagementWithOffices(engagement, new List<Subscribed_Offices__c>{subscribedOffice});
        
        Engagement_Assignee__c assignee = makeEngagementAssignee(engagement, personAccount);
        
        List<ace_File__c> filesSinceLookback = new List<ace_File__c>();
        filesSinceLookback.add(makeEngagementFile(engagement, subscribedOffice));
        filesSinceLookback.add(makeIndividualFile(personAccount, subscribedOffice));
        
		System.debug('files returned:: '+JSON.serialize(filesSinceLookback));
        
        aFilesStub.setReturnValue('getAceFilesAddedInWindowForNotification', filesSinceLookback);
        engagementsStub.setReturnValue('getEngagementsWithAllSubscribedOffices', new Map<Id, Engagement__c>{engagement.Id=>engagement});
        engagementsStub.setReturnValue('getMobileEmployeesByIndividualId', new List<Engagement_Assignee__c>{assignee});
        accountStub.setReturnValue('getFirmAccountsById', new Map<Id, Account>(returnedAccounts));
        
        FileNotificationJobService jobService = new FileNotificationJobService();
        jobService.aFiles = (ace_Files)aFilesStub.instance;
        jobService.engagements = (Engagements)engagementsStub.instance;
        jobService.accounts = (Accounts)accountStub.instance;
        
        FileNotificationJob job;
       
        test.startTest();
        
        job = jobService.makeFileNotificationJob(10,10);
        
        test.stopTest();
        
        
        aFilesStub.assertInvoked('getAceFilesAddedInWindowForNotification');
    }

   
	
    private static Account makeAccount(){
        Account fakeAccount = new Account(Name='Fake Account '+String.valueOf(DateTime.Now()), Id=TestUtility.getFakeId(Account.SObjectType), RelatedGroupId__c=TestUtility.getFakeId(Group.SObjectType));
        
        return fakeAccount;
    }
    
    private static Engagement__c makeEngagement(Account clientAccount, Account coordinatingOfficeAccount){
        String engagementString = new MobilityTestRecordBuilder()
                                    .withObjectType(engagement__c.SObjectType)
                                    .withParentRecords('Coordinating_Office__r', JSON.serialize(coordinatingOfficeAccount))
                                    .withParentRecords('Client__r', JSON.serialize(clientAccount))
                                    .withFields(new Map<String, String>{'Name'=>'Super Engagement'+String.valueOf(DateTime.Now())})
                                    .build()
                                    .getObjectString();
    
        return (Engagement__c)JSON.deserialize(engagementString, Engagement__c.class);
    }

    private static Engagement_Assignee__c makeEngagementAssignee(Engagement__c engagement, Account personaccount){
        String assigneeString = new MobilityTestRecordBuilder()
            					.withObjectType(Engagement_Assignee__c.SobjectType)
            					.withParentRecords('Engagements__r', JSON.serialize(engagement))
            					.withParentRecords('Assignee__r', JSON.serialize(personAccount))
                                .withFields(new Map<String, String>{'Assignee__c'=>personaccount.Id})
            					.build()
        						.getObjectString();
        System.debug('assignee : '+assigneeString);
        return (Engagement_Assignee__c)JSON.deserialize(assigneeString, Engagement_Assignee__c.class);
        
    }

    private static Engagement__c makeEngagementWithOffices(Engagement__c engagement, List<Subscribed_Offices__c> offices){
        List<String> subscribedOffices = new List<String>();
        String childString = '';
        
        for(Subscribed_offices__c office: offices){
            subscribedOffices.add(JSON.serialize(office));
        }
        
        String engagementString = new MobilityTestRecordBuilder()
            						.withObjectType(Engagement__c.sobjectType)
            						.withObjectString(JSON.serialize(engagement))
            						.withChildRecords('Subscribed_Office__r', subscribedOffices)
            						.build()
            						.getObjectString();
        
        return (Engagement__c)JSON.deserialize(engagementString, Engagement__c.class);
    }

    private static Subscribed_Offices__c makeSubscribedOffice(Engagement__c engagement, Account subscribedOfficeAccount){
        String subscribedOfficeString = new MobilityTestRecordBuilder()
                                            .withObjectType(Subscribed_Offices__c.SObjectType)
                                            .withFields(new Map<String, String>{'Engagement__c'=>engagement.Id, 'Account__c'=>subscribedOfficeAccount.Id})
                                            .withParentRecords('Engagement__r', JSON.serialize(engagement))
                                            .withParentRecords('Account__r', JSON.serialize(subscribedOfficeAccount))
                                            .build()
                                            .getObjectString();
        
    
        return (Subscribed_Offices__c)JSON.deserialize(subscribedOfficeString, Subscribed_Offices__c.class);
    }

   private static ace_File__c makeEngagementFile(Engagement__c engagement, Subscribed_Offices__c office){
        String userString = new MobilityTestRecordBuilder()
            .withObjectType(User.sObjectType)
            .withFields(new Map<String, String>{'UserType'=>'Standard'})
            .build()
            .getObjectString();
        String sharedFileString = new MobilityTestRecordBuilder()
            .withObjectType(ace_File__c.sObjectType)
            .withParentRecords('CreatedBy', userString)
            .withParentRecords('Engagement__r', JSON.serialize(engagement))
            .withParentRecords('Subscribed_Office__r', JSON.serialize(office))
            .withFields(new Map<String, String>{'Engagement__c'=>engagement.Id, 'Subscribed_Office__c' => office.Id, 'Work_Record__c'=>null, 'Individual__c'=>null})
            .build()
            .getObjectString();

        return (ace_File__c)JSON.deserialize(sharedFileString, ace_File__c.class);
    }

    private static ace_File__c makeIndividualFile(Account individual, Subscribed_Offices__c office){
    String userString = new MobilityTestRecordBuilder()
            .withObjectType(User.sObjectType)
            .withFields(new Map<String, String>{'UserType'=>'CustomerSuccess'})
            .build()
            .getObjectString();
        String sharedFileString = new MobilityTestRecordBuilder()
            .withObjectType(ace_File__c.sObjectType)
            .withParentRecords('CreatedBy', userString)
            .withParentRecords('Individual__r', JSON.serialize(individual))
            .withParentRecords('Subscribed_Office__r', JSON.serialize(office))
        	.withFields(new Map<String, String>{'Engagement__c'=>null,'Subscribed_Office__c' => office.Id, 'Work_Record__c'=>null, 'Individual__c'=>individual.Id, 'Subscribed_Office__c'=>office.Id})
            .build()
            .getObjectString();

        return (ace_File__c)JSON.deserialize(sharedFileString, ace_File__c.class);
    }
    
}