force-app/main/default/objects/Account/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.Firm_Type__c</field>
            <operation>equals</operation>
            <value>Member</value>
        </filterItems>
        <filterItems>
            <field>Account.Firm_Type__c</field>
            <operation>equals</operation>
            <value>Collaborating</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Partner Account)</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscribed_Offices__c/Subscribed_Offices__c.object-meta.xml
<CustomObject>
    <label>Subscribed Offices</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Subscribed Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscribed Office</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscribed_Offices__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscribed Office</relationshipLabel>
    <relationshipName>Subscribed_Office</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscribed_Offices__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>The country that this subscribed office is supporting.</description>
    <inlineHelpText>You can have more than one subscribed office entry for a country. You can also have more than one subscribed office for a firm when they support more than one country.</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SubscribedOfficeFromCountryActionTest.cls
@isTest 
public with sharing class SubscribedOfficeFromCountryActionTest {
    
    @isTest
    private static void itShouldReturnTheResult(){
        Id expected = TestUtility.getFakeId(Subscribed_Offices__c.SObjectType);
        
        String contactString = new MobilityTestRecordBuilder()
            .withObjectType(Contact.SobjectType)
            .build()
            .getObjectString();
        
        String accountString = new MobilityTestRecordBuilder()
            .withObjectType(Account.SObjectType)
            .withChildRecords('Contacts', new List<String>{contactString})
            .build()
            .getObjectString();
        
        String usOfficeString = new MobilityTestRecordBuilder()
            .withObjectType(Subscribed_Offices__c.sObjectType)
            .withRecordId(expected)
            .withParentRecords('Account__r', accountString)
            .withFields(new Map<String, String>{'Country__c'=>'AMERICA'})
            .build()
            .getObjectString();        
        
        String frOfficeString = new MobilityTestRecordBuilder()
            .withObjectType(Subscribed_Offices__c.sObjectType)
            .withRecordId(TestUtility.getFakeId(Subscribed_Offices__c.SObjectType))
            .withFields(new Map<String, String>{'Country__c'=>'FRANCE'})
            .build()
            .getObjectString();        
        
        
        List<Subscribed_Offices__c> offices = new List<Subscribed_Offices__c>(); 
        offices.add((Subscribed_Offices__c)JSON.deserialize(usOfficeString, Subscribed_Offices__c.class));
        offices.add((Subscribed_Offices__c)JSON.deserialize(frOfficeString, Subscribed_Offices__c.class));    
        
        Id actual;
        
        SubscribedOfficeFromCountryAction.Request req = new SubscribedOfficeFromCountryAction.Request();
        req.offices = offices;
        req.countryName = 'AMERICA';
        
        test.startTest();
        List<SubscribedOfficeFromCountryAction.Response> responses  = SubscribedOfficeFromCountryAction.SubscribedOfficeFromCountryAction(new List<SubscribedOfficeFromCountryAction.Request>{req});
        test.stopTest();
        
        System.assertEquals(1, responses.size(), 'expect one response');
        actual  = responses[0].subscribedOfficeId;
        System.assertEquals(expected, actual, 'expect the right ID to be returned');
    }
    
    @isTest
    private static void itShouldReturnNullWhenNoResult(){
        Id expected = null;
        
        String usOfficeString = new MobilityTestRecordBuilder()
            .withObjectType(Subscribed_Offices__c.sObjectType)
            .withRecordId(expected)
            .withFields(new Map<String, String>{'Country__c'=>'AMERICA'})
            .build()
            .getObjectString();        
        
        String frOfficeString = new MobilityTestRecordBuilder()
            .withObjectType(Subscribed_Offices__c.sObjectType)
            .withRecordId(TestUtility.getFakeId(Subscribed_Offices__c.SObjectType))
            .withFields(new Map<String, String>{'Country__c'=>'FRANCE'})
            .build()
            .getObjectString();        
        
        
        List<Subscribed_Offices__c> offices = new List<Subscribed_Offices__c>(); 
        offices.add((Subscribed_Offices__c)JSON.deserialize(usOfficeString, Subscribed_Offices__c.class));
        offices.add((Subscribed_Offices__c)JSON.deserialize(frOfficeString, Subscribed_Offices__c.class));    
        
        Id actual;
        
        SubscribedOfficeFromCountryAction.Request req = new SubscribedOfficeFromCountryAction.Request();
        req.offices = offices;
        req.countryName = 'AUSTRALIA';
        
        test.startTest();
        List<SubscribedOfficeFromCountryAction.Response> responses  = SubscribedOfficeFromCountryAction.SubscribedOfficeFromCountryAction(new List<SubscribedOfficeFromCountryAction.Request>{req});
        test.stopTest();
        
        System.assertEquals(1, responses.size(), 'expect one response');
        actual  = responses[0].subscribedOfficeId;
        System.assertEquals(expected, actual, 'expected a null result');
    }
}