force-app/main/default/objects/Account/fields/RelatedGroupId__c.field-meta.xml
<CustomField>
    <fullName>RelatedGroupId__c</fullName>
    <description>Stores the ID of the related public group for the Firm account.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>RelatedGroupId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ace_File__c/ace_File__c.object-meta.xml
<CustomObject>
    <description>Contains metadata associated to a file. This metadata persists even when the file itself is deleted.</description>
    <label>Shared File</label>
    <nameField>
        <displayFormat>af-{000000}</displayFormat>
        <label>File ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared Files</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/FileNotificationJob.cls
public with sharing class FileNotificationJob {
    
    private Integer emailChunkSize;
    private Integer lookbackWindow;
    
    @testVisible
    private FileNotificationQueue queue;
    @testVisible
    private FileNotificationAlertService notificationService;


    public FileNotificationJob(Integer emailChunkSize, Integer lookbackWindow){
        this.notificationService = new FileNotificationAlertService();
        this.queue = new FileNotificationQueue();
        this.emailChunkSize = emailChunkSize;
        this.lookbackWindow = lookbackWindow;
    }

    public void addItems(Request req){
        addToQueue(req);
    }

    public void addItems(List<Request> reqs){
        for(Request req : reqs){
            addToQueue(req);
        }
    }

    public void sendNotifications(){
        this.notificationService.sendNotifications(this.queue.getQueue(), 10);
    }

    public Boolean hasItems(){
        return this.queue.hasItems();
    }

    private void addToQueue(Request req){
        for(Account office : req.offices){
            System.debug('office:'+office);
            if(office.RelatedGroupId__c != null){
                this.queue.addFile(req.sharedFile, office.RelatedGroupId__c);
            }
            else{
                System.debug('the office, '+office.Name+', with the ID of '+office.Id+' does not have a RelatedGroupId. It cant be included in this queue');
            }
        }
    }


    public class Request{

        public ace_File__c sharedFile;
        public Set<Account> offices;

        public Request(ace_File__c sharedFile){
            this.sharedFile = sharedFile;
            this.offices = new Set<Account>();
        }

        public void addOffice(Account office){
            this.offices.add(office);
        }

        public void addOffices(Set<Account> officeAccounts){
            this.offices.addAll(officeAccounts);
        }
    }
}