force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Target</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not contracted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>A prospective, active or former corporate client</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Client_Contact.recordType-meta.xml
<RecordType>
    <fullName>Client_Contact</fullName>
    <active>true</active>
    <label>Client Contact</label>
</RecordType>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <displayFormat>ENG-{0000000000}</displayFormat>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement_Name_Tag__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Name_Tag__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Engagement Name Tag</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Target</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not Contracted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Information_Request__c/Information_Request__c.object-meta.xml
<CustomObject>
    <label>Information Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Information Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Information Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Information_Request__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <label>Assigned To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile Employee</fullName>
                <default>true</default>
                <label>Mobile Employee</label>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Andersen Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Information_Request__c/fields/Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contact at Client that will be assigned the Information Request</inlineHelpText>
    <label>Client Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Information Requests</relationshipLabel>
    <relationshipName>Information_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Information_Request__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Information Requests</relationshipLabel>
    <relationshipName>Information_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Information_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Action Required</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Internal Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Information_Request__c/fields/Work_Record__c.field-meta.xml
<CustomField>
    <fullName>Work_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Record</label>
    <referenceTo>Work_Record__c</referenceTo>
    <relationshipLabel>Information Requests</relationshipLabel>
    <relationshipName>Information_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/Work_Record__c.object-meta.xml
<CustomObject>
    <label>Work Record</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Record__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Work Records</relationshipLabel>
    <relationshipName>Work_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/fields/Net_Amount_in_Pocket__c.field-meta.xml
<CustomField>
    <fullName>Net_Amount_in_Pocket__c</fullName>
    <description>JIRA:AGMPB-312</description>
    <label>Net Amount in Pocket</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Non-Responder</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InformationRequestControllerTest.cls
@isTest
public class InformationRequestControllerTest {
    @testSetup
    static void setupTestData() {
        // Create Profile for Assignee Portal
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individual').getRecordTypeId();

        Account acc = new Account();
        
        acc.FirstName = 'Test';
        
        acc.LastName = 'Person Account';
        
        acc.RecordTypeId = accRecordTypeId;
        
        insert acc;
        
        Account assigneeAccount = [SELECT Id,IsPersonAccount, PersonContactId FROM Account WHERE Id =: acc.Id];
        
        System.assertEquals(true, assigneeAccount.isPersonAccount);
 
        Profile assigneeProfile = [SELECT Id FROM Profile WHERE Name = 'Assignee Portal' LIMIT 1];
        Profile clientProfile = [SELECT Id FROM Profile WHERE Name = 'Client Portal' LIMIT 1];
        //User clientUser = [SELECT Id FROM User WHERE ProfileId =: clientProfile.Id AND IsActive = True LIMIT 1];
        //User assigneeUser = [SELECT Id FROM User WHERE ProfileId =: assigneeProfile.Id AND IsActive = True LIMIT 1];
        // Create Users
        
        system.debug('ispersonAccount : ' + assigneeAccount.IsPersonAccount);
        system.debug('ispersonAccount : ' + assigneeAccount.PersonContactId);
        
        Id accRecordTypeId1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
		Id contRecordTypeId1 = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Client_Contact').getRecordTypeId();
        Account clientAccount = new Account(
            Name = 'Client Account',
            BillingStreet = '123 William Street',
            BillingCity = 'New York',
            BillingPostalCode = '10038',
            BillingState = 'New York',
            BillingStateCode = 'NY',
            BillingCountryCode = 'US',
            BillingCountry = 'United States',
            RecordTypeId = accRecordTypeId1
        );
        insert clientAccount;

        Contact clientContact = new Contact(
            AccountId = clientAccount.Id,
            LastName = 'ClientContact',
            FirstName = 'ClientFirstName',
            RecordTypeId = contRecordTypeId1
        );
        insert clientContact;
        
        system.debug('assigneeAccount.PersonContactId:'+assigneeAccount.PersonContactId);
        User assigneeUser = new User(
            Alias = 'assignee',
            Email = 'assignee@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Test',
            FirstName = 'Test',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = assigneeProfile.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'assignee@test.com',
            ContactId = assigneeAccount.PersonContactId
        );
        insert assigneeUser;
        
        User clientUser = new User(
            Alias = 'client',
            Email = 'client@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Client',
            FirstName = 'ClientTest',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = clientProfile.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'client@test.com',
            ContactId = clientContact.Id
        );
        insert clientUser;

        Engagement__c engagement = new Engagement__c(
            Engagement_Name_Tag__c = 'Test Engagement',
            Client__c = clientAccount.Id
        );
        insert engagement;

        Work_Record__c workRecord = new Work_Record__c(
           // Name = 'Test Work Record',
            Engagement__c = engagement.Id,
            Net_Amount_in_Pocket__c = 1234
        );
        insert workRecord;

        // Create Information Request records
        Information_Request__c request1 = new Information_Request__c(
           // Name = 'Request 1',
            Due_Date__c = Date.today().addDays(5),
            Status__c = 'Action Required',
            Assigned_To__c = 'Mobile Employee'
        );

        Information_Request__c request2 = new Information_Request__c(
          //  Name = 'Request 2',
            Due_Date__c = Date.today().addDays(10),
            Status__c = 'Action Required',
            Client_Contact__c = clientContact.Id,
            Assigned_To__c = 'Client',
            Work_Record__c = workRecord.Id
        );
        insert new List<Information_Request__c>{request1, request2};
    }

    @isTest
    static void testGetInformationRequestsForAssigneeProfile() {
        User assigneeUser = [SELECT Id FROM User WHERE Alias = 'assignee' LIMIT 1];
        System.runAs(assigneeUser) {
            List<Information_Request__c> requests = InformationRequestController.getInformationRequests(10, 0);
        }
    }

    @isTest
    static void testGetInformationRequestsForClientProfile() {
        User clientUser = [SELECT Id FROM User WHERE Alias = 'client' LIMIT 1];
        System.runAs(clientUser) {
            List<Information_Request__c> requests = InformationRequestController.getInformationRequests(10, 0);
        }
    }

    @isTest
    static void testGetInformationRequestCountForAssigneeProfile() {
        User assigneeUser = [SELECT Id FROM User WHERE Alias = 'assignee' LIMIT 1];
        System.runAs(assigneeUser) {
            Integer count = InformationRequestController.getInformationRequestCount();
        }
    }

    @isTest
    static void testGetInformationRequestCountForClientProfile() {
        User clientUser = [SELECT Id FROM User WHERE Alias = 'client' LIMIT 1];
        System.runAs(clientUser) {
            Integer count = InformationRequestController.getInformationRequestCount();
        }
    }
}