force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Target</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not contracted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>A prospective, active or former corporate client</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <displayFormat>ENG-{0000000000}</displayFormat>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Engagement_Name_Tag__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Name_Tag__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Engagement Name Tag</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Target</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not Contracted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/Engagement_Assignee__c.object-meta.xml
<CustomObject>
    <label>Mobile Employee</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Mobile Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobile Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Assignee__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mobile Employees</relationshipLabel>
    <relationshipName>Engagement_Assignees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/fields/Assignment_Country__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Country__c</fullName>
    <label>Relocation Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/fields/Engagements__c.field-meta.xml
<CustomField>
    <fullName>Engagements__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Mobile Employees</relationshipLabel>
    <relationshipName>Engagement_Assignees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Awaiting Andersen Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GlobalMobileUserMapControllerTest.cls
@IsTest
private class GlobalMobileUserMapControllerTest {
    
    @TestSetup
    static void setupTestData() {
        // Create a test Person Account for assignee
        Account testPersonAccount = new Account(
            LastName = 'Test Client Person Account',
            FirstName = 'ClientFirstName',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individual').getRecordTypeId()
        );
        insert testPersonAccount;

        // Query back the Person Account to get the PersonContactId
        testPersonAccount = [SELECT Id, PersonContactId FROM Account WHERE Id = :testPersonAccount.Id];

        // Create a test business Account for client
        Account clientAccount = new Account(
            Name = 'Test Client Account', 
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId()
        );
        insert clientAccount;

        // Create System Admin user to run as
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        User adminUser = new User(
            Username = 'admin.user.' + DateTime.now().getTime() + '@testorg.com',
            LastName = 'AdminUser',
            Firstname = 'Test 1',
            Email = 'admin.user@testorg.com',
            Alias = 'auser',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = adminProfile.Id,
            LanguageLocaleKey = 'en_US'
        );
        insert adminUser;

        // Create test Community User while running as System Admin
        System.runAs(adminUser) {
            Profile communityProfile = [SELECT Id FROM Profile WHERE Name LIKE '%Assignee%' and UserType LIKE '%Customer%' LIMIT 1];
            User testUser = new User(
                ContactId = testPersonAccount.PersonContactId,
                Username = 'test.user.' + DateTime.now().getTime() + '@testorg.com',
                LastName = 'TestUser',
                FirstName = 'testing',
                Email = 'test.user@testorg.com',
                Alias = 'tuser',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                EmailEncodingKey = 'UTF-8',
                ProfileId = communityProfile.Id,
                LanguageLocaleKey = 'en_US'
            );
            insert testUser;
        }

        // Create Engagement record with client Account
        Engagement__c engagement = new Engagement__c(
            Engagement_Name_Tag__c = 'Test',
            Client__c = clientAccount.Id,
            Status__c = 'Active'
        );
        insert engagement;

        // Create Engagement Assignees with different countries and proper Assignee__c
        List<Engagement_Assignee__c> assignees = new List<Engagement_Assignee__c>{
            new Engagement_Assignee__c(
                Engagements__c = engagement.Id,
                Assignment_Country__c = 'USA',
                Assignee__c = testPersonAccount.Id
            ),
            new Engagement_Assignee__c(
                Engagements__c = engagement.Id,
                Assignment_Country__c = 'GBR',
                Assignee__c = testPersonAccount.Id
            ),
            new Engagement_Assignee__c(
                Engagements__c = engagement.Id,
                Assignment_Country__c = 'USA',
                Assignee__c = testPersonAccount.Id
            )
        };
        insert assignees;
    }
    
    @IsTest
    static void testGetUserLocationsWithData() {
        User testUser = [SELECT Id, ContactId FROM User WHERE Username LIKE 'test.user.%' LIMIT 1];
        Account testPersonAccount = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Individual' LIMIT 1];
        
        // Debug information
        System.debug('Test User ContactId: ' + testUser.ContactId);
        System.debug('Test Person Account Id: ' + testPersonAccount.Id);
        
        Test.startTest();
        System.runAs(testUser) {
            GlobalMobileUserMapController.GeoJSONWrapper result = 
                GlobalMobileUserMapController.getUserLocations();
            
            // Debug the result
            System.debug('Result: ' + result);
            System.debug('Features: ' + result.features);
            
            System.assertEquals('FeatureCollection', result.type, 'Should be a FeatureCollection');
			//TODO: Fix feature shell is null
            // System.assertEquals(2, result.features.size(), 'Should have 2 unique countries');
            
            // Verify US count
            // GlobalMobileUserMapController.FeatureWrapper usFeature = 
            //     result.features.get(0);
            // System.assertEquals('USA', usFeature.id, 'Should have USA as feature');
            // System.assertEquals(2, usFeature.properties.count, 'Should have 2 US assignees');
        }
        Test.stopTest();
    }
    
    @IsTest
    static void testGetUserLocationsNoContact() {
        // Create standard user without contact
        Profile stdProfile = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User standardUser = new User(
            Username = 'std.user.' + DateTime.now().getTime() + '@testorg.com',
            LastName = 'StandardUser',
            FirstName = 'Test user',
            Email = 'standarduser@testorg.com',
            Alias = 'stduser',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = stdProfile.Id,
            LanguageLocaleKey = 'en_US'
        );
        insert standardUser;
        
        Test.startTest();
        System.runAs(standardUser) {
            GlobalMobileUserMapController.GeoJSONWrapper result = 
                GlobalMobileUserMapController.getUserLocations();
            
            System.assertEquals('FeatureCollection', result.type, 'Should be a FeatureCollection');
            System.assertEquals(0, result.features.size(), 'Should have no features');
        }
        Test.stopTest();
    }
    
    @IsTest
    static void testGetUserLocationsNoAssignees() {
        User testUser = [SELECT Id FROM User WHERE Username LIKE 'test.user.%' LIMIT 1];
        
        // Delete existing assignees
        delete [SELECT Id FROM Engagement_Assignee__c];
        
        Test.startTest();
        System.runAs(testUser) {
            GlobalMobileUserMapController.GeoJSONWrapper result = 
                GlobalMobileUserMapController.getUserLocations();
            
            System.assertEquals('FeatureCollection', result.type, 'Should be a FeatureCollection');
            System.assertEquals(0, result.features.size(), 'Should have no features');
        }
        Test.stopTest();
    }
    
}