force-app/main/default/objects/Information_Request__c/Information_Request__c.object-meta.xml
<CustomObject>
    <label>Information Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Information Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Information Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Information_Request__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <label>Assigned To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile Employee</fullName>
                <default>true</default>
                <label>Mobile Employee</label>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Andersen Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Information_Request__c/fields/Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contact at Client that will be assigned the Information Request</inlineHelpText>
    <label>Client Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Information Requests</relationshipLabel>
    <relationshipName>Information_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Information_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Action Required</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Internal Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Information_Request__c/fields/Work_Record_Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Work_Record_Name_Formula__c</fullName>
    <formula>Work_Record__r.Name</formula>
    <label>Work Record</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InformationRequestController.cls
public with sharing class InformationRequestController {
    @AuraEnabled
    public static List<Information_Request__c> getInformationRequests(Integer limitSize, Integer offset) {
        Id profileId=userinfo.getProfileId();
        String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
        
        if (profileName == 'Assignee Portal') {
            return [
            SELECT Id, Name, Work_Record_Name_Formula__c, Due_Date__c 
            FROM Information_Request__c
            WHERE Status__c =  'Action Required' AND Assigned_To__c = 'Mobile Employee'
            ORDER BY Due_Date__c DESC LIMIT :limitSize OFFSET :offset
            ];
        }else {
            Id currentContactId = [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId()].ContactId;
            return [
            SELECT Id, Name, Work_Record_Name_Formula__c, Due_Date__c 
            FROM Information_Request__c
            WHERE Client_Contact__c = :currentContactId AND Status__c =  'Action Required' AND Assigned_To__c = 'Client'
            ORDER BY Due_Date__c DESC LIMIT :limitSize OFFSET :offset
            ];
        }
        
    }
    @AuraEnabled
    public static Integer getInformationRequestCount(){
        AggregateResult results;
        Id profileId=userinfo.getProfileId();
        String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
        List<Information_Request__c> irList = new List<Information_Request__c>();
        if (profileName == 'Assignee Portal') {
            results = [
            SELECT Count(Id) TotalIR
            FROM Information_Request__c
            WHERE Status__c =  'Action Required' AND Assigned_To__c = 'Mobile Employee'
            ];
        }else {
            Id currentContactId = [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId()].ContactId;
            results = [
            SELECT Count(Id) TotalIR
            FROM Information_Request__c
            WHERE Client_Contact__c = :currentContactId AND Status__c =  'Action Required' AND Assigned_To__c = 'Client'
            ];
        }
        Integer TotalIR = (Integer)results.get('TotalIR');
        return TotalIR;
    } 
}