force-app/main/default/objects/Information_Request__c/Information_Request__c.object-meta.xml
<CustomObject>
    <label>Information Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Information Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Information Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Information_Request__c/fields/Work_Record__c.field-meta.xml
<CustomField>
    <fullName>Work_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Record</label>
    <referenceTo>Work_Record__c</referenceTo>
    <relationshipLabel>Information Requests</relationshipLabel>
    <relationshipName>Information_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/Work_Record__c.object-meta.xml
<CustomObject>
    <label>Work Record</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Record__c/fields/Work_Record_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Record_Contact_Email__c</fullName>
    <description>JIRA:AGMPB-409</description>
    <formula>Work_Record_Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Record Contact Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/fields/Work_Record_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Work_Record_Contact_Name__c</fullName>
    <description>Jira:AGMPB-409</description>
    <formula>Work_Record_Contact__r.FirstName &amp; &quot; &quot; &amp; Work_Record_Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Record Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Record__c/fields/Work_Record_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Work_Record_Contact_Phone__c</fullName>
    <description>jira:AGMPB-409</description>
    <formula>Work_Record_Contact__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Record Contact Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AssigneePortalTaxConsultantController.cls
public without sharing class AssigneePortalTaxConsultantController {
    @AuraEnabled
    public static List<UserWrapper> getTopUsers(String informationRequestId) {
        List<Information_Request__c> infoRequests = [
            SELECT Id, 
                   Work_Record__r.Work_Record_Contact_Email__c, 
                   Work_Record__r.Work_Record_Contact_Phone__c, 
                   Work_Record__r.Work_Record_Contact_Name__c 
            FROM Information_Request__c 
            WHERE Id = :informationRequestId
        ];
        
        List<UserWrapper> userList = new List<UserWrapper>();
        
        for (Information_Request__c record : infoRequests) {
            userList.add(new UserWrapper(
                record.Work_Record__r.Work_Record_Contact_Name__c,
                record.Work_Record__r.Work_Record_Contact_Email__c,
                record.Work_Record__r.Work_Record_Contact_Phone__c
            ));
        }

        return userList;
    }

    public class UserWrapper {
        @AuraEnabled public String Name;
        @AuraEnabled public String Email;
        @AuraEnabled public String Phone;

        public UserWrapper(String Name, String Email, String Phone) {
            this.Name = Name;
            this.Email = Email;
            this.Phone = Phone;
        }
    }

}