force-app/main/default/objects/Contact/fields/Country_Location_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Location_Name__c</fullName>
    <description>JIRA:AGMPB-785</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Country (Location) Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <displayFormat>ENG-{0000000000}</displayFormat>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/fields/Global_Relationship_Partner__c.field-meta.xml
<CustomField>
    <fullName>Global_Relationship_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Relationship Partner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/Engagement_Assignee__c.object-meta.xml
<CustomObject>
    <label>Mobile Employee</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Mobile Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobile Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Assignee__c/fields/Assignment_Country__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Country__c</fullName>
    <label>Relocation Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/fields/Engagements__c.field-meta.xml
<CustomField>
    <fullName>Engagements__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Mobile Employees</relationshipLabel>
    <relationshipName>Engagement_Assignees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/acx_PortalEmailsControllerTest.cls
@isTest
public class acx_PortalEmailsControllerTest {

    @isTest
    static void itShouldPopulateEmailDataFromEngagementAssignee(){
        // Stub EngagementAssignees to return a fake Engagement_Assignee__c
        Stub engagementAssigneesStub = new Stub(EngagementAssignees.class);

        Engagement_Assignee__c fakeAssignee = new Engagement_Assignee__c();
        fakeAssignee.Assignment_Country__c = 'Germany';
        // Use JSON trick to populate nested relationship names without DML
        String engagementJson = '{"Engagements__r":{"Client__r":{"Name":"Acme Corp"}}}';
        fakeAssignee = (Engagement_Assignee__c)JSON.deserialize(
            JSON.serialize(fakeAssignee).substring(0, JSON.serialize(fakeAssignee).length()-1) + ',' +
            engagementJson.substring(1),
            Engagement_Assignee__c.class
        );

        engagementAssigneesStub.setReturnValue('getEngagementAssigneeWithCriteria', new List<Engagement_Assignee__c>{ fakeAssignee });

        acx_PortalEmailsController controller = new acx_PortalEmailsController();
        controller.engagementAssignees = (EngagementAssignees) engagementAssigneesStub.instance;
        controller.assigneeRecordId = TestUtility.getFakeId(User.SObjectType);

        Test.startTest();
        acx_PortalEmailsController.EmailData data = controller.getEmailData();
        Test.stopTest();

        System.assertEquals('Acme Corp', data.clientName, 'clientName should come from Engagements__r.Client__r.Name');
        System.assertEquals('Germany', data.hostCountry, 'hostCountry should come from Assignment_Country__c');
    }

    @isTest
    static void itShouldFallbackToContactWhenNoAssigneeFound(){
        // Stub EngagementAssignees to return empty and Contacts to return a fake Contact with Account
        Stub engagementAssigneesStub = new Stub(EngagementAssignees.class);
        engagementAssigneesStub.setReturnValue('getEngagementAssigneeWithCriteria', new List<Engagement_Assignee__c>());

        Stub contactsStub = new Stub(Contacts.class);
        Account fakeAccount = (Account)JSON.deserialize('{"Name":"Globex"}', Account.class);
        Contact fakeContact = (Contact)JSON.deserialize('{"Account":' + JSON.serialize(fakeAccount) + ',"Country_Location_Name__c":"Canada"}', Contact.class);
        contactsStub.setReturnValue('getContactByUserId', new List<Contact>{ fakeContact });

        acx_PortalEmailsController controller = new acx_PortalEmailsController();
        controller.engagementAssignees = (EngagementAssignees) engagementAssigneesStub.instance;
        controller.contacts = (Contacts) contactsStub.instance;
        controller.assigneeRecordId = TestUtility.getFakeId(User.SObjectType);

        Test.startTest();
        acx_PortalEmailsController.EmailData data = controller.getEmailData();
        Test.stopTest();

        System.assertEquals('Globex', data.clientName, 'clientName should come from Contact.Account.Name');
        System.assertEquals('Canada', data.hostCountry, 'hostCountry should come from Contact.Country_Location_Name__c');
    }

    @isTest
    static void itShouldRemainEmptyWhenNoIdsOrData(){
        acx_PortalEmailsController controller = new acx_PortalEmailsController();
        // Do not set assigneeRecordId → initialize should not run

        Test.startTest();
        acx_PortalEmailsController.EmailData data = controller.getEmailData();
        Test.stopTest();

        System.assertEquals('', data.clientName, 'clientName should remain empty by default');
        System.assertEquals('', data.hostCountry, 'hostCountry should remain empty by default');
    }
}