force-app/main/default/objects/Contact/fields/Country_Location_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Location_Name__c</fullName>
    <description>JIRA:AGMPB-785</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Country (Location) Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <displayFormat>ENG-{0000000000}</displayFormat>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/Engagement_Assignee__c.object-meta.xml
<CustomObject>
    <label>Mobile Employee</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Mobile Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobile Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Assignee__c/fields/Assignment_Country__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Country__c</fullName>
    <label>Relocation Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engagement_Assignee__c/fields/Engagements__c.field-meta.xml
<CustomField>
    <fullName>Engagements__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Mobile Employees</relationshipLabel>
    <relationshipName>Engagement_Assignees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/acx_PortalEmailsController.cls
public without sharing class acx_PortalEmailsController {
    @testVisible
    private EngagementAssignees engagementAssignees;
    @testVisible
    private Contacts contacts;
    
    public class EmailData {
        public String clientName { get; set; }
        public String hostCountry { get; set; }
        
        public EmailData() {
            this.clientName = '';
            this.hostCountry = '';
        }
    }
    
    private EmailData emailDataInternal;
    public Id assigneeRecordId { get; set; }
    private Boolean initialized = false;
    
    public acx_PortalEmailsController() {
        this.engagementAssignees = new EngagementAssignees();
        this.contacts = new Contacts();
        this.emailDataInternal = new EmailData();
    }
    
    private void initialize() {
        if (!initialized && assigneeRecordId != null) {
            try {
                List<Engagement_Assignee__c> assigneeResults = 
                    this.engagementAssignees.getEngagementAssigneeWithCriteria(this.assigneeRecordId);
                
                if (assigneeResults != null && !assigneeResults.isEmpty()) {
                    Engagement_Assignee__c assigneeRecord = assigneeResults[0];
                    
                    if (assigneeRecord.Engagements__r != null && 
                        assigneeRecord.Engagements__r.Client__r != null) {
                        this.emailDataInternal.clientName = assigneeRecord.Engagements__r.Client__r.Name;
                    }
                    this.emailDataInternal.hostCountry = assigneeRecord.Assignment_Country__c;
                } else {
                    List<Contact> contactResults = 
                        this.contacts.getContactByUserId(this.assigneeRecordId);
                    
                    if (contactResults != null && !contactResults.isEmpty()) {
                        Contact clientContact = contactResults[0];
                        
                        if (clientContact.Account != null) {
                            this.emailDataInternal.clientName = clientContact.Account.Name;
                        }
                        this.emailDataInternal.hostCountry = clientContact.Country_Location_Name__c;
                    }
                }
                
            } catch (Exception e) {
                System.debug(LoggingLevel.ERROR, 'Error initializing email data: ' + e.getMessage());
            } finally {
                initialized = true;
            }
        }
    }
    
    public EmailData getEmailData() {
        initialize();
        return this.emailDataInternal;
    }
}